<?php
require_once __DIR__.'/../../config.php';
require_once __DIR__.'/../../includes/functions.php';
require_once __DIR__.'/../../includes/assinaturas_usuarios.php';
$token=(string)($_GET['token']??'');$convite=assinaturaConvitePorToken($pdo,$token);$disponivel=$convite&&assinaturaConviteDisponivel($convite);$doc=$convite['documento']??[];
$estado='Convite inválido ou não encontrado.';
if($convite){if(($convite['status']??'')==='UTILIZADO'||(int)($doc['assinado']??0)===1)$estado='Este certificado já foi assinado.';elseif(($convite['status']??'')==='CANCELADO')$estado='Este convite foi cancelado. Solicite um novo e-mail.';elseif(strtotime((string)$convite['expira_em'])<time())$estado='Este convite expirou. Solicite o reenvio do e-mail.';elseif(($convite['status']??'')==='PROCESSANDO')$estado='A assinatura deste certificado está sendo processada.';}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Assinar certificado</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf4f1;color:#153b32;font-family:Inter,Arial,sans-serif}.top{background:#063e33;color:#fff;padding:24px}.top div{max-width:1180px;margin:auto}.wrap{max-width:1180px;margin:24px auto;padding:0 16px}.card{background:#fff;border-radius:14px;box-shadow:0 8px 30px #163d3320;overflow:hidden}.summary{padding:22px;display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.item{border:1px solid #d8e6e1;border-radius:9px;padding:12px}.item small{display:block;color:#657b75;margin-bottom:5px}.pdf{height:68vh;border:0;border-top:1px solid #dce8e4;width:100%;background:#eee}.actions{padding:20px;border-top:1px solid #dce8e4}.agree{display:flex;gap:10px;align-items:flex-start;padding:14px;background:#f2f8f6;border-radius:9px}.btn{display:inline-block;border:0;border-radius:8px;padding:13px 20px;background:#07966d;color:#fff;font-weight:700;text-decoration:none;cursor:pointer;margin-top:14px}.btn.secondary{background:#327b9b;margin-left:8px}.btn:disabled{opacity:.55;cursor:not-allowed}.msg{padding:14px;border-radius:8px;margin-top:12px;display:none}.error{background:#fee8e7;color:#8d231d}.success{background:#e3f7ee;color:#086342}.closed{padding:38px;text-align:center}.closed h2{color:#7e332d}@media(max-width:760px){.summary{grid-template-columns:1fr 1fr}.pdf{height:58vh}}@media(max-width:480px){.summary{grid-template-columns:1fr}}
</style></head><body><header class="top"><div><h1 style="margin:0">Autorização de assinatura</h1><p style="margin:7px 0 0;opacity:.85">Amazon Certificadora</p></div></header><main class="wrap"><section class="card">
<?php if(!$disponivel): ?><div class="closed"><h2>Assinatura indisponível</h2><p><?=h($estado)?></p></div>
<?php else: ?><div class="summary"><div class="item"><small>Certificado</small><strong><?=h($convite['documento_tipo'])?></strong></div><div class="item"><small>Número</small><strong><?=h($doc['numero']??'')?></strong></div><div class="item"><small>Embarcação</small><strong><?=h($doc['nome_embarcacao']??'')?></strong></div><div class="item"><small>Responsável</small><strong><?=h($convite['nome_completo'])?></strong></div><div class="item"><small>Emissão</small><strong><?=!empty($doc['data_emissao'])?h(date('d/m/Y',strtotime($doc['data_emissao']))):'—'?></strong></div><div class="item"><small>Validade</small><strong><?=!empty($doc['data_validade'])?h(date('d/m/Y',strtotime($doc['data_validade']))):'—'?></strong></div><div class="item"><small>Convite válido até</small><strong><?=h(date('d/m/Y H:i',strtotime($convite['expira_em'])))?></strong></div><div class="item"><small>Assinatura utilizada</small><strong>Cadastrada no perfil</strong></div></div>
<iframe class="pdf" title="Prévia completa do certificado" src="<?=APP_URL.'assinatura-certificado/'.rawurlencode($token).'/pdf'?>"></iframe><div class="actions"><p>Revise o PDF acima. Ao confirmar, a assinatura manuscrita cadastrada será aplicada e sua localização, IP, navegador, data e hora serão registrados.</p><label class="agree"><input type="checkbox" id="aceite"> <span>Li o documento e autorizo a aplicação da minha assinatura neste certificado.</span></label><button class="btn" id="assinar">Autorizar e assinar</button><a class="btn secondary" target="_blank" href="<?=APP_URL.'assinatura-certificado/'.rawurlencode($token).'/pdf'?>">Abrir PDF</a><div id="msg" class="msg"></div></div>
<script>(function(){const b=document.getElementById('assinar'),a=document.getElementById('aceite'),m=document.getElementById('msg');function show(t,e){m.style.display='block';m.className='msg '+(e?'error':'success');m.textContent=t}b.onclick=()=>{if(!a.checked){show('Marque a autorização após revisar o PDF.',true);return}if(!navigator.geolocation){show('Este navegador não oferece geolocalização.',true);return}b.disabled=true;show('Obtendo localização...',false);navigator.geolocation.getCurrentPosition(pos=>{const f=new FormData();f.append('csrf_token',<?=json_encode(gerarCSRF())?>);f.append('aceite','1');f.append('latitude',pos.coords.latitude);f.append('longitude',pos.coords.longitude);f.append('geo_precisao_m',pos.coords.accuracy||'');fetch(<?=json_encode(APP_URL.'assinatura-certificado/'.$token.'/confirmar')?>,{method:'POST',body:f,credentials:'same-origin'}).then(async r=>{const d=await r.json().catch(()=>({success:false,message:'Resposta inválida.'}));if(!r.ok||!d.success)throw new Error(d.message||'Falha ao assinar.');show(d.message,false);b.style.display='none';a.disabled=true;if(d.validation_url){const l=document.createElement('a');l.href=d.validation_url;l.className='btn secondary';l.textContent='Validar documento assinado';m.after(l)}}).catch(e=>{show(e.message,true);b.disabled=false})},e=>{show(e.code===1?'A localização é obrigatória para assinar.':'Não foi possível obter a localização.',true);b.disabled=false},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}})();</script>
<?php endif; ?></section></main></body></html>
