<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/feedback.php';verificar_sessao();if(getCargo()!=='ADMIN'){setMensagem('error','Acesso restrito aos administradores.');redirecionar(APP_URL.'feedback');}
$cargos=['VENDEDOR'=>'Vendedor','VISTORIADOR'=>'Vistoriador','ANALISTA'=>'Analista'];$escopos=['ADMIN'=>'Caixa Admin','TODOS_USUARIOS'=>'Todos os usuários','GESTOR_DIRETO'=>'Gestor direto','SUBORDINADOS'=>'Equipe direta','OUTROS_GESTORES'=>'Outros gestores'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verificarCSRF($_POST['csrf_token']??'')){setMensagem('error','Token de segurança inválido.');redirecionar(APP_URL.'feedback/configuracoes');}
 try{$pdo->beginTransaction();$pdo->exec("UPDATE feedback_regras_comunicacao SET ativo=0 WHERE escopo<>'CARGO'");$up=$pdo->prepare("INSERT INTO feedback_regras_comunicacao (id,cargo_origem,escopo,cargo_destino,ativo) VALUES (:id,:cargo,:escopo,NULL,1) ON DUPLICATE KEY UPDATE ativo=1");foreach($cargos as $cargo=>$x)foreach($escopos as $escopo=>$y)if(!empty($_POST['regra'][$cargo][$escopo]))$up->execute([':id'=>gerarUUID(),':cargo'=>$cargo,':escopo'=>$escopo]);
 $pdo->exec("UPDATE feedback_regras_comunicacao SET ativo=0 WHERE escopo='CARGO'");$up=$pdo->prepare("INSERT INTO feedback_regras_comunicacao (id,cargo_origem,escopo,cargo_destino,ativo) VALUES (:id,:origem,'CARGO',:destino,1) ON DUPLICATE KEY UPDATE ativo=1");foreach($cargos as $origem=>$x)foreach(array_keys($cargos) as $destino)if(!empty($_POST['cargo'][$origem][$destino]))$up->execute([':id'=>gerarUUID(),':origem'=>$origem,':destino'=>$destino]);$pdo->commit();setMensagem('success','Regras de comunicação atualizadas.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();setMensagem('error','Não foi possível salvar as regras.');error_log($e->getMessage());}redirecionar(APP_URL.'feedback/configuracoes');
}
$rows=$pdo->query('SELECT cargo_origem,escopo,cargo_destino,ativo FROM feedback_regras_comunicacao')->fetchAll();$on=[];foreach($rows as $r)if($r['ativo'])$on[$r['cargo_origem']][$r['escopo']][$r['cargo_destino']??'']=true;
$titulo_page='Configurar Feedback';require __DIR__.'/../../includes/header.php';?>
<div class="feedback-page"><a class="feedback-back" href="<?=APP_URL?>configuracoes"><i class="fa-solid fa-arrow-left"></i> Configurações</a><header class="feedback-title"><div><h1>Regras de comunicação</h1><p>Defina os destinos disponíveis para cada cargo.</p></div></header><form class="feedback-card" method="post"><input type="hidden" name="csrf_token" value="<?=h(gerarCSRF())?>"><div class="feedback-matrix"><table><thead><tr><th>Cargo de origem</th><?php foreach($escopos as $v):?><th><?=h($v)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($cargos as $cargo=>$label):?><tr><th><?=h($label)?></th><?php foreach($escopos as $escopo=>$label2):?><td><input type="checkbox" name="regra[<?=$cargo?>][<?=$escopo?>]" value="1" <?=!empty($on[$cargo][$escopo][''])?'checked':''?>></td><?php endforeach;?></tr><?php endforeach;?></tbody></table><h2>Comunicação direta entre cargos</h2><table><thead><tr><th>Origem \ destino</th><?php foreach($cargos as $v):?><th><?=h($v)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($cargos as $origem=>$label):?><tr><th><?=h($label)?></th><?php foreach($cargos as $destino=>$label2):?><td><input type="checkbox" name="cargo[<?=$origem?>][<?=$destino?>]" value="1" <?=!empty($on[$origem]['CARGO'][$destino])?'checked':''?>></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><button class="btn btn-primary">Salvar regras</button></form></div><?php require __DIR__.'/../../includes/footer.php';?>
