<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/feedback.php';verificar_sessao();$u=(string)$_SESSION['usuario_id'];$id=trim($_GET['id']??'');
$participante=feedbackPodeParticipar($pdo,$id,$u);$auditoria=!$participante&&feedbackPodeAuditar($pdo,$id,$u);
if(!$participante&&!$auditoria){http_response_code(404);setMensagem('error','Conversa não encontrada.');redirecionar(APP_URL.'feedback');}
if($participante)feedbackMarcarLida($pdo,$id,$u);
$q=$pdo->prepare('SELECT f.*,r.nome remetente_nome,d.nome destinatario_nome,p.arquivado_em FROM feedbacks f JOIN usuarios r ON r.id=f.remetente_id LEFT JOIN usuarios d ON d.id=f.destinatario_id LEFT JOIN feedback_participantes p ON p.feedback_id=f.id AND p.usuario_id=:u WHERE f.id=:id');$q->execute([':u'=>$u,':id'=>$id]);$f=$q->fetch();
$q=$pdo->prepare('SELECT m.*,u.nome autor_nome,u.cargo autor_cargo FROM feedback_mensagens m JOIN usuarios u ON u.id=m.autor_id WHERE m.feedback_id=:id ORDER BY m.criado_em');$q->execute([':id'=>$id]);$msgs=$q->fetchAll();
$q=$pdo->prepare('SELECT a.* FROM feedback_anexos a JOIN feedback_mensagens m ON m.id=a.mensagem_id WHERE m.feedback_id=:id ORDER BY a.criado_em');$q->execute([':id'=>$id]);$an=[];foreach($q->fetchAll() as $a)$an[$a['mensagem_id']][]=$a;
$titulo_page='Conversa - Feedback';require __DIR__.'/../../includes/header.php';?>
<div class="feedback-page feedback-thread-page"><a href="<?=APP_URL?>feedback<?=$auditoria?'?aba=auditoria':''?>" class="feedback-back"><i class="fa-solid fa-arrow-left"></i> Voltar à Central</a><?php if($auditoria):?><div class="feedback-audit-notice"><i class="fa-solid fa-eye"></i><span><strong>Modo somente auditoria</strong> Esta consulta não altera a leitura dos participantes e não permite intervenção.</span></div><?php else:?><div class="feedback-compliance"><i class="fa-solid fa-shield-halved"></i> As mensagens internas podem ser consultadas pelos administradores para fins de segurança e conformidade.</div><?php endif;?><header class="feedback-thread-head"><div><span><?=h(feedbackCategorias()[$f['categoria']])?></span><h1><?=h($f['remetente_nome'])?> → <?=h($f['destinatario_nome']?:'Admin')?></h1><small>Aberta em <?=date('d/m/Y H:i',strtotime($f['criado_em']))?></small></div><div><em class="feedback-priority p-<?=strtolower($f['prioridade'])?>"><?=h(feedbackPrioridades()[$f['prioridade']])?></em><b class="feedback-status"><?=h(feedbackStatus()[$f['status']])?></b></div></header>
<section class="feedback-thread"><?php foreach($msgs as $m):?><article class="feedback-message <?=$m['autor_id']===$u?'is-mine':''?>"><header><strong><?=h($m['autor_nome'])?></strong><time><?=date('d/m/Y H:i',strtotime($m['criado_em']))?></time></header><div class="feedback-message-text"><?=nl2br(h($m['texto']))?></div><?php if(!empty($an[$m['id']])):?><div class="feedback-attachments"><?php foreach($an[$m['id']] as $a):$img=str_starts_with($a['tipo_mime'],'image/');?><a href="<?=APP_URL?>feedback/arquivo?id=<?=urlencode($a['id'])?><?=$img?'':'&download=1'?>" <?=$img?'target="_blank"':''?>><?php if($img):?><img src="<?=APP_URL?>feedback/arquivo?id=<?=urlencode($a['id'])?>" alt="<?=h($a['nome_arquivo'])?>"><?php else:?><i class="fa-regular fa-file-lines"></i><?php endif;?><span><?=h($a['nome_arquivo'])?><small><?=number_format($a['tamanho']/1024,1,',','.')?> KB</small></span></a><?php endforeach;?></div><?php endif;?></article><?php endforeach;?></section>
<?php if($participante):?><section class="feedback-card feedback-reply"><form method="post" action="<?=APP_URL?>feedback/actions" enctype="multipart/form-data" data-feedback-upload><input type="hidden" name="csrf_token" value="<?=h(gerarCSRF())?>"><input type="hidden" name="action" value="responder"><input type="hidden" name="feedback_id" value="<?=h($id)?>"><textarea name="texto" rows="4" maxlength="20000" placeholder="Escreva uma resposta..." required></textarea><input type="file" name="anexos[]" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.docx,.xlsx,.pptx,.csv,.txt"><div class="feedback-preview"></div><button class="btn btn-primary">Responder</button></form><div class="feedback-thread-actions"><form method="post" action="<?=APP_URL?>feedback/actions"><input type="hidden" name="csrf_token" value="<?=h(gerarCSRF())?>"><input type="hidden" name="action" value="status"><input type="hidden" name="feedback_id" value="<?=h($id)?>"><input type="hidden" name="status" value="<?=$f['status']==='RESOLVIDO'?'ABERTO':'RESOLVIDO'?>"><button class="btn"><?=$f['status']==='RESOLVIDO'?'Reabrir':'Marcar resolvida'?></button></form><form method="post" action="<?=APP_URL?>feedback/actions"><input type="hidden" name="csrf_token" value="<?=h(gerarCSRF())?>"><input type="hidden" name="action" value="arquivar"><input type="hidden" name="feedback_id" value="<?=h($id)?>"><button class="btn"><?=$f['arquivado_em']?'Desarquivar':'Arquivar'?></button></form></div></section><?php endif;?></div>
<?php require __DIR__.'/../../includes/footer.php';?>
