<?php
require_once __DIR__.'/../../config.php';
require_once __DIR__.'/../../includes/functions.php';
require_once __DIR__.'/../../includes/auth.php';
require_once __DIR__.'/../../includes/assinaturas_usuarios.php';
verificar_sessao();
$usuarioId=(string)($_SESSION['usuario_id']??'');$cargo=getCargo();$itens=assinaturaPendencias($pdo,$usuarioId,$cargo);$token=trim((string)($_GET['token']??''));
$titulo_page='Minhas assinaturas';require_once __DIR__.'/../../includes/header.php';require_once __DIR__.'/../../includes/sidebar.php';
?>
<div class="main-content" id="mainContent"><div class="page-header"><div><h1><i class="fas fa-file-signature"></i> Minhas assinaturas</h1><p><?= $cargo==='ADMIN'?'Documentos pendentes e relatórios aprovados que permitem assinatura substituta.':'Documentos que aguardam a sua assinatura cadastrada.' ?></p></div></div>
<?php if(!$itens): ?><div class="empty-state"><i class="fas fa-circle-check"></i><h3>Nenhuma assinatura pendente</h3><p>Os documentos atribuídos a você aparecerão aqui.</p></div><?php else: ?>
<div class="table-container"><table class="data-table"><thead><tr><th>Documento</th><th>Número</th><th>Embarcação</th><th>Data</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php foreach($itens as $item): $itemToken=(string)($item['token_assinatura']??''); ?>
<tr <?= $token!==''&&hash_equals($itemToken,$token)?'style="background:#e8f7ef"':'' ?>><td><strong><?=h($item['tipo'])?></strong></td><td><?=h($item['numero']?:'Sem número')?></td><td><?=h($item['nome_embarcacao'])?></td><td><?=!empty($item['data_emissao'])?formatarData($item['data_emissao']):'—'?></td><td><span class="badge badge-warning">Aguardando assinatura</span></td><td style="display:flex;gap:6px">
<?php if($item['tipo']==='RELATORIO'): ?><a target="_blank" class="btn btn-sm btn-secondary" href="<?=APP_URL?>vistorias/relatorio_pdf?id=<?=urlencode($item['id'])?>"><i class="fas fa-eye"></i></a><?php elseif($item['tipo']==='PARECER_PLANOS'): ?><a target="_blank" class="btn btn-sm btn-secondary" href="<?=APP_URL?>analises-planos/parecer-pdf?id=<?=urlencode($item['id'])?>"><i class="fas fa-eye"></i></a><?php else: ?><a target="_blank" class="btn btn-sm btn-secondary" href="<?=APP_URL.h($item['origem'])?>"><i class="fas fa-list"></i></a><?php endif; ?>
<button type="button" class="btn btn-sm btn-success js-assinar"
        data-tipo="<?=h($item['tipo'])?>"
        data-id="<?=h($item['id'])?>"
        data-substituta="<?=!empty($item['assinatura_substituta'])?'1':'0'?>"
        data-vistoriador="<?=h($item['vistoriador_nome']??'')?>"><i class="fas fa-pen-nib"></i> Assinar</button>
<?php if(in_array($item['tipo'],['CSN','CNBL','CNARQ'],true)): ?><form method="post" action="<?=APP_URL?>minhas-assinaturas/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="reenviar"><input type="hidden" name="tipo" value="<?=h($item['tipo'])?>"><input type="hidden" name="id" value="<?=h($item['id'])?>"><button class="btn btn-sm btn-warning" title="Reenviar e-mail"><i class="fas fa-envelope"></i></button></form><?php endif; ?>
</td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div id="modalAssinatura" style="display:none;position:fixed;inset:0;background:rgba(4,35,28,.62);z-index:10050;align-items:center;justify-content:center;padding:18px"><div style="background:#fff;border-radius:14px;width:min(540px,100%);overflow:hidden"><div style="padding:20px;background:#073f34;color:#fff"><strong>Confirmar assinatura</strong></div><div style="padding:22px"><p id="assinaturaDescricao">Será aplicada a assinatura manuscrita cadastrada no seu perfil. Sua localização, IP, data e hora serão registrados.</p><div id="assinaturaMsg" class="alert" style="display:none"></div></div><div style="padding:15px 22px;background:#f4f7f6;display:flex;justify-content:flex-end;gap:10px"><button class="btn btn-secondary" id="cancelarAssinatura">Cancelar</button><button class="btn btn-success" id="confirmarAssinatura"><i class="fas fa-location-dot"></i> Permitir localização e assinar</button></div></div></div>
<script>(function(){let atual=null;const modal=document.getElementById('modalAssinatura'),msg=document.getElementById('assinaturaMsg'),descricao=document.getElementById('assinaturaDescricao'),confirmar=document.getElementById('confirmarAssinatura');function mensagem(t,e){msg.style.display='block';msg.className='alert '+(e?'alert-danger':'alert-info');msg.textContent=t}document.querySelectorAll('.js-assinar').forEach(b=>b.addEventListener('click',()=>{atual=b;msg.style.display='none';descricao.textContent=b.dataset.substituta==='1'?'Será aplicada, como assinatura substituta, a assinatura cadastrada do vistoriador atribuído '+(b.dataset.vistoriador||'ao relatório')+'. O vistoriador permanecerá como responsável técnico e sua identidade de administrador será registrada como executora da ação.':'Será aplicada a assinatura manuscrita cadastrada no seu perfil. Sua localização, IP, data e hora serão registrados.';modal.style.display='flex'}));document.getElementById('cancelarAssinatura').onclick=()=>{modal.style.display='none';atual=null};confirmar.onclick=()=>{if(!atual)return;if(!navigator.geolocation){mensagem('Este navegador não oferece geolocalização.',true);return}confirmar.disabled=true;mensagem('Obtendo localização...',false);navigator.geolocation.getCurrentPosition(pos=>{const fd=new FormData();fd.append('csrf_token',<?=json_encode(gerarCSRF())?>);fd.append('action','assinar');fd.append('documento_tipo',atual.dataset.tipo);fd.append('documento_id',atual.dataset.id);fd.append('latitude',pos.coords.latitude);fd.append('longitude',pos.coords.longitude);fd.append('geo_precisao_m',pos.coords.accuracy||'');fetch(<?=json_encode(APP_URL.'minhas-assinaturas/actions')?>,{method:'POST',body:fd,credentials:'same-origin'}).then(async r=>{const d=await r.json().catch(()=>({success:false,message:'Resposta inválida.'}));if(!r.ok||!d.success)throw new Error(d.message||'Falha ao assinar.');mensagem(d.message,false);setTimeout(()=>location.reload(),800)}).catch(e=>{mensagem(e.message,true);confirmar.disabled=false})},e=>{mensagem(e.code===1?'A localização é obrigatória para assinar.':'Não foi possível obter a localização.',true);confirmar.disabled=false},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}})();</script>
<?php require_once __DIR__.'/../../includes/footer.php'; ?>
