<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/analise_planos.php';require_once __DIR__.'/../../includes/aprovacao_ui.php';analisePlanosExigirAcesso();
$id=trim($_GET['id']??'');$a=null;$submissoes=[];$itens=[];$exigencias=[];$pareceres=[];$historico=[];
if($id){try{$a=analisePlanosCarregar($pdo,$id);}catch(Throwable $e){setMensagem('error',$e->getMessage());redirecionar(APP_URL.'analises-planos');}
 $s=$pdo->prepare('SELECT s.*,u.nome usuario_nome FROM analise_planos_submissoes s LEFT JOIN usuarios u ON u.id=s.criado_por WHERE s.analise_id=:id ORDER BY s.revisao DESC');$s->execute([':id'=>$id]);$submissoes=$s->fetchAll(PDO::FETCH_ASSOC);
 foreach($submissoes as &$sub){$q=$pdo->prepare('SELECT * FROM analise_planos_arquivos WHERE submissao_id=:id ORDER BY criado_em');$q->execute([':id'=>$sub['id']]);$sub['arquivos']=$q->fetchAll(PDO::FETCH_ASSOC);}unset($sub);
 $q=$pdo->prepare('SELECT * FROM analise_planos_itens WHERE analise_id=:id ORDER BY ordem,id');$q->execute([':id'=>$id]);$itens=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare('SELECT * FROM analise_planos_exigencias WHERE analise_id=:id ORDER BY ordem,id');$q->execute([':id'=>$id]);$exigencias=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare('SELECT p.*,u.nome criador_nome FROM analise_planos_pareceres p LEFT JOIN usuarios u ON u.id=p.criado_por WHERE p.analise_id=:id ORDER BY p.versao DESC');$q->execute([':id'=>$id]);$pareceres=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare('SELECT h.*,u.nome usuario_nome FROM analise_planos_historico h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE h.analise_id=:id ORDER BY h.criado_em DESC LIMIT 30');$q->execute([':id'=>$id]);$historico=$q->fetchAll(PDO::FETCH_ASSOC);
}
$embarcacoes=$pdo->query("SELECT id,nome,COALESCE(NULLIF(registro,''),numero_inscricao) registro FROM embarcacoes WHERE ativo=1 ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);$clientes=$pdo->query("SELECT id,nome,perfil FROM clientes WHERE status='ATIVO' ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);$analistas=$pdo->query("SELECT DISTINCT u.id,u.nome FROM usuarios u LEFT JOIN usuario_perfis p ON p.usuario_id=u.id WHERE u.ativo=1 AND (u.cargo IN ('ADMIN','ANALISTA') OR p.perfil='ANALISTA') ORDER BY u.nome")->fetchAll(PDO::FETCH_ASSOC);$responsaveis=$pdo->query("SELECT id,nome_completo,cargo_titulo FROM responsaveis_assinatura WHERE ativo=1 ORDER BY nome_completo")->fetchAll(PDO::FETCH_ASSOC);
$editavel=!$a||!in_array($a['status'],['CONCLUIDA','REPROVADA','CANCELADA'],true);$analiseAberta=$a&&in_array($a['status'],['RASCUNHO','EM_ANALISE','AGUARDANDO_CORRECAO'],true);$titulo_page=($a?$a['numero']:'Nova Análise').' - Análise de Planos';require_once __DIR__.'/../../includes/header.php';
?>
<div class="conteudo-principal analise-planos-page">
 <div class="form-container"><div class="form-header"><h3><i class="fas fa-drafting-compass"></i> <?=$a?h($a['numero']):'Nova análise de planos'?></h3><a class="btn btn-secondary btn-sm" href="<?=APP_URL?>analises-planos"><i class="fas fa-arrow-left"></i> Voltar</a></div>
 <?php if($a):?><div class="analise-summary"><span><b>Situação</b><?=h(str_replace('_',' ',$a['status']))?></span><span><b>Embarcação</b><?=h($a['embarcacao_nome'])?></span><span><b>Atualização</b><?=formatarDataCompleta($a['atualizado_em'])?></span></div><?php endif?>
 <form method="post" action="<?=APP_URL?>analises-planos/actions" class="form-padrao"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar"><input type="hidden" name="id" value="<?=h($id)?>">
  <h4>Identificação do processo</h4><div class="form-row"><div class="form-group col-6"><label>Embarcação *</label><select name="embarcacao_id" required <?=$editavel?'':'disabled'?>><?php foreach($embarcacoes as $e):?><option value="<?=h($e['id'])?>" <?=($a['embarcacao_id']??'')===$e['id']?'selected':''?>><?=h($e['nome'].($e['registro']?' · '.$e['registro']:''))?></option><?php endforeach?></select></div><div class="form-group col-3"><label>Processo *</label><select name="tipo_processo" <?=$editavel?'':'disabled'?>><?php foreach(['LC','LCEC','LA','LR','OUTRO'] as $v):?><option <?=($a['tipo_processo']??'LC')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div><div class="form-group col-3"><label>Enquadramento *</label><select name="enquadramento" <?=$editavel?'':'disabled'?>><?php foreach(['NORMAM-201','NORMAM-202','OUTRO'] as $v):?><option <?=($a['enquadramento']??'NORMAM-202')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div></div>
  <div class="form-row"><div class="form-group col-6"><label>Objeto da análise *</label><input name="objeto" required value="<?=h($a['objeto']??'')?>" placeholder="Ex.: Licença de Construção de embarcação de passageiros" <?=$editavel?'':'disabled'?>></div><div class="form-group col-6"><label>Solicitante</label><select name="solicitante_id" <?=$editavel?'':'disabled'?>><option value="">Não informado</option><?php foreach($clientes as $c):?><option value="<?=h($c['id'])?>" <?=($a['solicitante_id']??'')===$c['id']?'selected':''?>><?=h($c['nome'].' · '.$c['perfil'])?></option><?php endforeach?></select></div></div>
  <div class="form-row"><div class="form-group col-3"><label>Estaleiro</label><input name="estaleiro" value="<?=h($a['estaleiro']??'')?>" <?=$editavel?'':'disabled'?>></div><div class="form-group col-3"><label>Nº do casco</label><input name="numero_casco" value="<?=h($a['numero_casco']??'')?>" <?=$editavel?'':'disabled'?>></div><div class="form-group col-3"><label>Responsável pelo projeto</label><input name="responsavel_projeto_nome" value="<?=h($a['responsavel_projeto_nome']??'')?>" <?=$editavel?'':'disabled'?>></div><div class="form-group col-3"><label>Registro/CREA</label><input name="responsavel_projeto_registro" value="<?=h($a['responsavel_projeto_registro']??'')?>" <?=$editavel?'':'disabled'?>></div></div>
  <div class="form-row"><div class="form-group col-3"><label>ART</label><input name="art_numero" value="<?=h($a['art_numero']??'')?>" <?=$editavel?'':'disabled'?>></div><div class="form-group col-4"><label>Analista *</label><select name="analista_id" <?=getCargo()==='ADMIN'&&$editavel?'':'disabled'?>><?php foreach($analistas as $u):?><option value="<?=h($u['id'])?>" <?=($a['analista_id']??($_SESSION['usuario_id']??''))===$u['id']?'selected':''?>><?=h($u['nome'])?></option><?php endforeach?></select><?php if(getCargo()!=='ADMIN'):?><input type="hidden" name="analista_id" value="<?=h($_SESSION['usuario_id'])?>"><?php endif?></div><div class="form-group col-5"><label>Responsável técnico pela assinatura</label><select name="responsavel_assinatura_id" <?=$editavel?'':'disabled'?>><option value="">Selecione</option><?php foreach($responsaveis as $r):?><option value="<?=$r['id']?>" <?=((int)($a['responsavel_assinatura_id']??0)===(int)$r['id'])?'selected':''?>><?=h($r['nome_completo'].' · '.$r['cargo_titulo'])?></option><?php endforeach?></select></div></div>
  <div class="form-group"><label>Observações gerais</label><textarea name="observacoes" rows="3" <?=$editavel?'':'disabled'?>><?=h($a['observacoes']??'')?></textarea></div><?php if($editavel):?><div class="form-actions"><button class="btn btn-primary"><i class="fas fa-save"></i> Salvar processo</button></div><?php endif?>
 </form></div>

 <?php if($a):?>
 <section class="analise-card"><h3><i class="fas fa-cloud-arrow-up"></i> Revisões e arquivos</h3><?php if($analiseAberta):?><form method="post" enctype="multipart/form-data" action="<?=APP_URL?>analises-planos/actions" class="analise-inline-form"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="adicionar_submissao"><input type="hidden" name="analise_id" value="<?=h($id)?>"><select name="categoria"><?php foreach(analisePlanosCategoriasPadrao() as $cat):?><option><?=h($cat)?></option><?php endforeach?></select><input type="date" name="recebido_em" value="<?=date('Y-m-d')?>" required><input name="descricao" placeholder="Descrição da revisão"><input type="file" name="arquivos[]" multiple required accept=".pdf,.jpg,.jpeg,.png,.dwg,.dxf,.doc,.docx,.xls,.xlsx"><button class="btn btn-primary"><i class="fas fa-upload"></i> Adicionar revisão</button></form><?php endif?>
 <?php if(!$submissoes):?><p class="text-muted">Nenhuma revisão recebida.</p><?php endif;foreach($submissoes as $s):?><div class="revision-block"><strong>Revisão <?=$s['revisao']?></strong><span><?=formatarData($s['recebido_em'])?> · <?=h($s['descricao']??'Sem descrição')?></span><div><?php foreach($s['arquivos'] as $arq):?><a class="file-pill" href="<?=APP_URL?>analises-planos/arquivo?id=<?=urlencode($arq['id'])?>" target="_blank"><i class="fas fa-file"></i><?=h($arq['nome_original'])?><small><?=number_format($arq['tamanho_bytes']/1024,0,',','.')?> KB</small></a><?php endforeach?></div></div><?php endforeach?></section>

 <section class="analise-card"><h3><i class="fas fa-list-check"></i> Matriz de análise</h3><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar_itens"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="portal-table-wrap"><table><thead><tr><th>#</th><th>Documento/requisito</th><th>Revisão</th><th>Referência</th><th>Resultado</th><th>Observação</th></tr></thead><tbody><?php foreach($itens as $i=>$item):?><tr><td><?=$i+1?><input type="hidden" name="item_id[]" value="<?=h($item['id'])?>"></td><td><input name="documento[]" value="<?=h($item['documento'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><input name="revisao_documento[]" value="<?=h($item['revisao_documento'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><input name="referencia_normativa[]" value="<?=h($item['referencia_normativa'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><select name="resultado[]" <?=$analiseAberta?'':'disabled'?>><?php foreach(['PENDENTE','CONFORME','EXIGENCIA','NAO_APLICA'] as $v):?><option value="<?=$v?>" <?=$item['resultado']===$v?'selected':''?>><?=str_replace('_',' ',$v)?></option><?php endforeach?></select></td><td><textarea name="item_observacao[]" rows="2" <?=$analiseAberta?'':'disabled'?>><?=h($item['observacao'])?></textarea></td></tr><?php endforeach?></tbody></table></div><?php if($analiseAberta):?><div class="analise-inline-form"><input name="novo_documento" placeholder="Novo requisito"><input name="nova_referencia" placeholder="Referência normativa"><button class="btn btn-primary"><i class="fas fa-save"></i> Salvar matriz</button></div><?php endif?></form></section>

 <section class="analise-card"><h3><i class="fas fa-triangle-exclamation"></i> Exigências</h3><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar_exigencias"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="portal-table-wrap"><table><thead><tr><th>#</th><th>Descrição</th><th>Referência</th><th>Prazo</th><th>Situação</th><th>Cumprimento</th></tr></thead><tbody><?php foreach($exigencias as $i=>$ex):?><tr><td><?=$i+1?><input type="hidden" name="exigencia_id[]" value="<?=h($ex['id'])?>"></td><td><textarea name="exigencia_descricao[]" rows="2" <?=$analiseAberta?'':'disabled'?>><?=h($ex['descricao'])?></textarea></td><td><input name="exigencia_referencia[]" value="<?=h($ex['referencia_normativa'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><input type="date" name="exigencia_prazo[]" value="<?=h($ex['prazo'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><select name="exigencia_status[]" <?=$analiseAberta?'':'disabled'?>><?php foreach(['PENDENTE','CUMPRIDA','PARCIAL','TRANSCRITA'] as $v):?><option <?=$ex['status']===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></td><td><textarea name="exigencia_observacao[]" rows="2" <?=$analiseAberta?'':'disabled'?>><?=h($ex['observacao_cumprimento'])?></textarea></td></tr><?php endforeach?></tbody></table></div><?php if($analiseAberta):?><div class="analise-inline-form"><textarea name="nova_exigencia" placeholder="Nova exigência"></textarea><input name="nova_exigencia_referencia" placeholder="Referência"><input type="date" name="nova_exigencia_prazo"><button class="btn btn-primary"><i class="fas fa-save"></i> Salvar exigências</button></div><?php endif?></form></section>

 <section class="analise-card" id="pareceres"><h3><i class="fas fa-file-signature"></i> Pareceres</h3><?php if(in_array($a['status'],['EM_ANALISE','AGUARDANDO_CORRECAO'],true)):?><form method="post" action="<?=APP_URL?>analises-planos/actions" class="form-padrao"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="criar_parecer"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="form-row"><div class="form-group col-4"><label>Resultado</label><select name="resultado"><?php foreach(['EXIGENCIAS'=>'Relatório de exigências','APROVADO'=>'Aprovado','APROVADO_COM_EXIGENCIAS'=>'Aprovado com exigências','REPROVADO'=>'Reprovado'] as $v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach?></select></div><div class="form-group col-8"><label>Responsável técnico</label><select name="responsavel_assinatura_id" required><option value="">Selecione</option><?php foreach($responsaveis as $r):?><option value="<?=$r['id']?>" <?=((int)($a['responsavel_assinatura_id']??0)===(int)$r['id'])?'selected':''?>><?=h($r['nome_completo'].' · '.$r['cargo_titulo'])?></option><?php endforeach?></select></div></div><div class="form-group"><label>Resumo</label><textarea name="resumo" required rows="3"></textarea></div><div class="form-group"><label>Conclusão</label><textarea name="conclusao" required rows="4"></textarea></div><button class="btn btn-primary"><i class="fas fa-paper-plane"></i> Enviar para aprovação</button></form><?php endif?>
 <?php if(!$pareceres):?><p class="text-muted">Nenhum parecer emitido.</p><?php endif;foreach($pareceres as $p):?><article class="parecer-row"><div><strong>Parecer v<?=$p['versao']?> · <?=h(str_replace('_',' ',$p['resultado']))?></strong><span><?=h($p['status'])?> · <?=formatarDataCompleta($p['criado_em'])?></span></div><div><a class="btn btn-secondary btn-sm" target="_blank" href="<?=APP_URL?>analises-planos/parecer-pdf?id=<?=urlencode($p['id'])?>"><i class="fas fa-eye"></i> PDF</a><?php renderBotaoAprovacaoDocumento($pdo,'PARECER_PLANOS',$p['id'],$p['status'],$p['status']==='PUBLICADO',(int)$p['responsavel_assinatura_id']);?></div></article><?php endforeach?></section>

 <section class="analise-card"><h3><i class="fas fa-clock-rotate-left"></i> Histórico</h3><div class="timeline"><?php foreach($historico as $h):?><div><strong><?=h($h['evento'])?></strong><span><?=h($h['usuario_nome'])?> · <?=formatarDataCompleta($h['criado_em'])?></span><?php if($h['detalhe']):?><p><?=h($h['detalhe'])?></p><?php endif?></div><?php endforeach?></div></section>
 <?php endif?>
</div>
<style>
.analise-planos-page{display:grid;gap:18px}.analise-card{background:var(--cor-card,#fff);border:1px solid var(--cor-borda,#ddd);border-radius:12px;padding:20px}.analise-card h3{margin:0 0 16px}.analise-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:14px 20px;background:rgba(30,136,229,.08)}.analise-summary span{display:flex;flex-direction:column;gap:4px}.analise-inline-form{display:flex;align-items:end;gap:10px;flex-wrap:wrap;margin:12px 0}.analise-inline-form>*{flex:1;min-width:140px}.revision-block{padding:14px 0;border-top:1px solid var(--cor-borda,#ddd)}.revision-block>span{margin-left:10px;color:var(--cor-texto-secundario,#777)}.file-pill{display:inline-flex;gap:7px;align-items:center;margin:10px 8px 0 0;padding:8px 10px;border:1px solid var(--cor-borda,#ddd);border-radius:8px}.file-pill small{opacity:.7}.analise-card table input,.analise-card table select,.analise-card table textarea{min-width:120px;width:100%}.parecer-row{display:flex;justify-content:space-between;align-items:center;padding:14px 0;border-top:1px solid var(--cor-borda,#ddd)}.parecer-row>div:first-child{display:flex;flex-direction:column;gap:5px}.timeline>div{border-left:3px solid #2596be;padding:2px 0 14px 14px}.timeline span{display:block;font-size:.85rem;opacity:.7}.timeline p{margin:5px 0}@media(max-width:800px){.analise-summary{grid-template-columns:1fr}.parecer-row{align-items:flex-start;gap:12px;flex-direction:column}}
</style>
<?php renderAprovacaoUi($pdo); require_once __DIR__.'/../../includes/footer.php';?>
