<?php
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/analise_planos.php';
analisePlanosExigirAcesso();

$id = trim($_GET['id'] ?? '');
if ($id === '') {
    setMensagem('error', 'Novas análises são criadas automaticamente por propostas assinadas.');
    redirecionar(APP_URL . 'analises-planos');
}
try {
    $a = analisePlanosCarregar($pdo, $id);
} catch (Throwable $e) {
    setMensagem('error', $e->getMessage());
    redirecionar(APP_URL . 'analises-planos');
}

$submissoes = [];
$q = $pdo->prepare('SELECT s.*,u.nome usuario_nome,c.nome portal_nome FROM analise_planos_submissoes s LEFT JOIN usuarios u ON u.id=s.criado_por LEFT JOIN clientes c ON c.id=s.portal_cliente_id WHERE s.analise_id=:id ORDER BY s.revisao DESC');
$q->execute([':id'=>$id]);
$submissoes = $q->fetchAll(PDO::FETCH_ASSOC);
foreach ($submissoes as &$sub) {
    $q = $pdo->prepare('SELECT ar.*,i.documento item_documento,u.nome classificador_nome FROM analise_planos_arquivos ar LEFT JOIN analise_planos_itens i ON i.id=ar.item_id LEFT JOIN usuarios u ON u.id=ar.classificado_por WHERE ar.submissao_id=:id ORDER BY ar.criado_em');
    $q->execute([':id'=>$sub['id']]);
    $sub['arquivos']=$q->fetchAll(PDO::FETCH_ASSOC);
}
unset($sub);
$q=$pdo->prepare('SELECT * FROM analise_planos_itens WHERE analise_id=:id ORDER BY ordem,id');$q->execute([':id'=>$id]);$itens=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare('SELECT * FROM analise_planos_exigencias WHERE analise_id=:id ORDER BY ordem,id');$q->execute([':id'=>$id]);$exigencias=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare('SELECT p.*,u.nome criador_nome FROM analise_planos_pareceres p LEFT JOIN usuarios u ON u.id=p.criado_por WHERE p.analise_id=:id ORDER BY p.versao DESC');$q->execute([':id'=>$id]);$pareceres=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare('SELECT h.*,u.nome usuario_nome FROM analise_planos_historico h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE h.analise_id=:id ORDER BY h.criado_em DESC LIMIT 60');$q->execute([':id'=>$id]);$historico=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare('SELECT ah.*,ua.nome analista_anterior_nome,un.nome analista_novo_nome,u.nome autor_nome FROM analise_planos_agenda_historico ah LEFT JOIN usuarios ua ON ua.id=ah.analista_anterior_id LEFT JOIN usuarios un ON un.id=ah.analista_novo_id LEFT JOIN usuarios u ON u.id=ah.criado_por WHERE ah.analise_id=:id ORDER BY ah.criado_em DESC');$q->execute([':id'=>$id]);$agendaHistorico=$q->fetchAll(PDO::FETCH_ASSOC);
$q=$pdo->prepare('SELECT id,numero_lc,tipo_licenca,status,assinado FROM certificados_lc WHERE analise_id=:id LIMIT 1');$q->execute([':id'=>$id]);$licenca=$q->fetch(PDO::FETCH_ASSOC);
$analistas=$pdo->query("SELECT DISTINCT u.id,u.nome FROM usuarios u LEFT JOIN usuario_perfis p ON p.usuario_id=u.id WHERE u.ativo=1 AND u.excluido_em IS NULL AND (u.cargo='ANALISTA' OR p.perfil='ANALISTA') ORDER BY u.nome")->fetchAll(PDO::FETCH_ASSOC);
$propostasLegado=[];$servicosLegado=[];$vendedoresLegado=[];
if(getCargo()==='ADMIN'&&(empty($a['proposta_id'])||empty($a['servico_id'])||empty($a['vendedor_origem_id']))){
 $q=$pdo->prepare("SELECT id,numero FROM propostas WHERE cliente_id=:cliente AND status='assinada' ORDER BY data_emissao DESC,numero DESC LIMIT 100");$q->execute([':cliente'=>$a['solicitante_id']]);$propostasLegado=$q->fetchAll(PDO::FETCH_ASSOC);
 $servicosLegado=$pdo->query("SELECT id,nome,codigo_operacional FROM servicos WHERE ativo=1 AND codigo_operacional IN ('ANALISE_PLANOS_EC1','ANALISE_PLANOS_EC2') ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);
 $vendedoresLegado=$pdo->query("SELECT id,nome FROM usuarios WHERE ativo=1 AND excluido_em IS NULL AND cargo='VENDEDOR' ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);
}

$cargo=getCargo();$usuario=(string)($_SESSION['usuario_id']??'');
$podeTecnico=$cargo==='ANALISTA'&&$a['analista_id']===$usuario;
$origemComercialCompleta=!empty($a['proposta_id'])&&!empty($a['servico_id'])&&!empty($a['vendedor_origem_id']);
$podeAgenda=($cargo==='ADMIN'||($cargo==='VENDEDOR'&&$a['vendedor_origem_id']===$usuario)||($cargo==='ANALISTA'&&$a['analista_id']===$usuario))&&$origemComercialCompleta;
$iniciada=!empty($a['iniciado_em'])||in_array($a['status'],['EM_ANALISE','AGUARDANDO_DOCUMENTOS','AGUARDANDO_ASSINATURA_ANALISTA','AGUARDANDO_APROVACAO_ADMIN','CONCLUIDA'],true);
$tecnicoEditavel=$podeTecnico&&in_array($a['status'],['AGENDADA','EM_ANALISE','AGUARDANDO_DOCUMENTOS'],true);
$analiseAberta=$podeTecnico&&in_array($a['status'],['EM_ANALISE','AGUARDANDO_DOCUMENTOS'],true);
$statusLabels=['AGUARDANDO_AGENDAMENTO'=>'Aguardando agendamento','AGENDADA'=>'Agendada','EM_ANALISE'=>'Em análise','AGUARDANDO_DOCUMENTOS'=>'Aguardando documentos','AGUARDANDO_ASSINATURA_ANALISTA'=>'Aguardando assinatura do analista','AGUARDANDO_APROVACAO_ADMIN'=>'Aguardando admin','CONCLUIDA'=>'Concluída','REPROVADA'=>'Reprovada','CANCELADA'=>'Cancelada'];
$protocolos=[];if(podeAcessar('protocolos_documentais')){try{$q=$pdo->prepare('SELECT id,numero,assunto,status FROM protocolo_dossies WHERE analise_id=:id ORDER BY criado_em');$q->execute([':id'=>$id]);$protocolos=$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}}
$titulo_page=$a['numero'].' - Análise de Planos';
require_once __DIR__ . '/../../includes/header.php';
?>
<div class="conteudo-principal analise-planos-page">
 <div class="form-container">
  <div class="form-header"><div><h3><i class="fas fa-drafting-compass"></i> <?=h($a['numero'])?></h3><small><?=h($a['proposta_numero'] ?: 'Processo histórico sem proposta')?> · <?=h($a['servico_nome'] ?: 'Serviço não vinculado')?></small></div><a class="btn btn-secondary btn-sm" href="<?=APP_URL?>analises-planos"><i class="fas fa-arrow-left"></i> Voltar</a></div>
  <div class="analise-summary"><span><b>Situação</b><?=h($statusLabels[$a['status']]??$a['status'])?></span><span><b>Embarcação</b><?=h($a['embarcacao_nome'])?></span><span><b>Vendedor de origem</b><?=h($a['vendedor_origem_nome'] ?: 'Legado')?></span><span><b>Analista</b><?=h($a['analista_nome'] ?: 'Não atribuído')?></span><span><b>Prazo</b><?=!empty($a['prazo_agendado_em'])?formatarDataCompleta($a['prazo_agendado_em']):'Não agendado'?></span></div>
 </div>

 <?php if(podeAcessar('protocolos_documentais')): ?><section class="analise-card"><h3><i class="fas fa-arrow-right-arrow-left"></i> Tramitação documental</h3><p>O protocolo registra custódia e envio; a baixa técnica das exigências continua sendo feita somente pelos relatórios de ciclo.</p><?php foreach($protocolos as $prot): ?><p><a href="<?= APP_URL ?>protocolos/form?id=<?= urlencode($prot['id']) ?>"><strong><?= h($prot['numero']) ?></strong> · <?= h($prot['assunto']) ?></a> <span class="badge"><?= h($prot['status']) ?></span></p><?php endforeach; ?><?php if(!$protocolos): ?><p class="text-muted">Nenhum dossiê vinculado.</p><?php endif; ?><a class="btn btn-secondary btn-sm" href="<?= APP_URL ?>protocolos/form?analise_id=<?= urlencode($id) ?>&embarcacao_id=<?= urlencode($a['embarcacao_id']) ?>"><i class="fas fa-plus"></i> Abrir protocolo deste processo</a></section><?php endif; ?>

 <?php if($cargo==='ADMIN'&&!$origemComercialCompleta):?>
 <section class="analise-card"><h3><i class="fas fa-link"></i> Vincular origem do processo legado</h3>
  <p class="alert alert-warning">Este processo foi preservado, mas não poderá ser agendado nem gerar uma nova licença até receber os vínculos comerciais.</p>
  <form method="post" action="<?=APP_URL?>analises-planos/actions" class="analise-inline-form">
   <input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="vincular_legado"><input type="hidden" name="analise_id" value="<?=h($id)?>">
   <div><label>Proposta assinada *</label><select name="proposta_id" required><option value="">Selecione</option><?php foreach($propostasLegado as $p):?><option value="<?=h($p['id'])?>"><?=h($p['numero'])?></option><?php endforeach?></select></div>
   <div><label>Serviço de análise *</label><select name="servico_id" required><option value="">Selecione</option><?php foreach($servicosLegado as $s):?><option value="<?=h($s['id'])?>"><?=h($s['nome'])?></option><?php endforeach?></select></div>
   <div><label>Vendedor de origem *</label><select name="vendedor_origem_id" required><option value="">Selecione</option><?php foreach($vendedoresLegado as $v):?><option value="<?=h($v['id'])?>"><?=h($v['nome'])?></option><?php endforeach?></select></div>
   <button class="btn btn-primary"><i class="fas fa-link"></i> Vincular origem</button>
  </form>
 </section>
 <?php endif?>

 <?php if($podeAgenda&&!in_array($a['status'],['CONCLUIDA','REPROVADA','CANCELADA'],true)):?>
 <section class="analise-card"><h3><i class="fas fa-calendar-check"></i> Agenda da análise</h3>
  <form method="post" action="<?=APP_URL?>analises-planos/actions" class="analise-inline-form">
   <input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="agendar"><input type="hidden" name="analise_id" value="<?=h($id)?>">
   <div><label>Analista *</label><select name="analista_id" required <?=($iniciada&&$cargo!=='ADMIN')?'disabled':''?>><option value="">Selecione</option><?php foreach($analistas as $u):?><option value="<?=h($u['id'])?>" <?=$a['analista_id']===$u['id']?'selected':''?>><?=h($u['nome'])?></option><?php endforeach?></select><?php if($iniciada&&$cargo!=='ADMIN'):?><input type="hidden" name="analista_id" value="<?=h($a['analista_id'])?>"><?php endif?></div>
   <div><label>Prazo *</label><input type="datetime-local" name="prazo_agendado_em" value="<?=!empty($a['prazo_agendado_em'])?date('Y-m-d\TH:i',strtotime($a['prazo_agendado_em'])):''?>" required></div>
   <div><label>Motivo <?=!empty($a['prazo_agendado_em'])?'*':''?></label><input name="motivo" maxlength="500" placeholder="<?=!empty($a['prazo_agendado_em'])?'Obrigatório no reagendamento':'Agendamento inicial'?>"></div>
   <button class="btn btn-primary"><i class="fas fa-calendar-check"></i> <?=!empty($a['prazo_agendado_em'])?'Reagendar':'Agendar'?></button>
  </form>
  <?php if($agendaHistorico):?><div class="timeline"><?php foreach($agendaHistorico as $ag):?><div><strong><?=h($ag['acao'])?> · <?=formatarDataCompleta($ag['prazo_novo_em'])?></strong><span><?=h($ag['autor_nome'])?> · <?=formatarDataCompleta($ag['criado_em'])?></span><p><?=h($ag['motivo'])?></p></div><?php endforeach?></div><?php endif?>
 </section>
 <?php endif?>

 <?php if($podeTecnico&&$a['status']==='AGENDADA'):?><section class="analise-card"><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="iniciar"><input type="hidden" name="analise_id" value="<?=h($id)?>"><button class="btn btn-primary"><i class="fas fa-play"></i> Iniciar análise técnica</button></form></section><?php endif?>

 <section class="analise-card"><h3><i class="fas fa-ship"></i> Enquadramento técnico</h3>
  <form method="post" action="<?=APP_URL?>analises-planos/actions" class="form-padrao"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar"><input type="hidden" name="id" value="<?=h($id)?>">
   <div class="form-row"><div class="form-group col-3"><label>Processo *</label><select name="tipo_processo" required <?=$tecnicoEditavel?'':'disabled'?>><?php foreach(analisePlanosTiposPermitidos() as $v):?><option value="<?=$v?>" <?=$a['tipo_processo']===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div><div class="form-group col-3"><label>Norma *</label><select name="enquadramento" required <?=$tecnicoEditavel?'':'disabled'?>><?php foreach(analisePlanosNormasPermitidas() as $v):?><option value="<?=$v?>" <?=$a['enquadramento']===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div><div class="form-group col-3"><label>Classe</label><input value="<?=h($a['classe_certificacao'])?>" disabled></div><div class="form-group col-3"><label>Arqueação bruta</label><input type="number" step="0.01" min="0" name="arqueacao_bruta" value="<?=h($a['arqueacao_bruta'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div></div>
   <div class="form-row"><div class="form-group col-3"><label>Passageiros</label><input type="number" min="0" name="numero_passageiros" value="<?=h($a['numero_passageiros'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-3"><label>Propulsão</label><select name="possui_propulsao" <?=$tecnicoEditavel?'':'disabled'?>><option value="">A definir</option><option value="1" <?=$a['possui_propulsao']==='1'?'selected':''?>>Com propulsão</option><option value="0" <?=$a['possui_propulsao']==='0'?'selected':''?>>Sem propulsão</option></select></div><div class="form-group col-3"><label>Classificada</label><select name="embarcacao_classificada" <?=$tecnicoEditavel?'':'disabled'?>><option value="">A definir</option><option value="1" <?=$a['embarcacao_classificada']==='1'?'selected':''?>>Sim</option><option value="0" <?=$a['embarcacao_classificada']==='0'?'selected':''?>>Não</option></select></div><div class="form-group col-3"><label>Construção concluída</label><select name="construcao_concluida" <?=$tecnicoEditavel?'':'disabled'?>><option value="">A definir</option><option value="1" <?=$a['construcao_concluida']==='1'?'selected':''?>>Sim</option><option value="0" <?=$a['construcao_concluida']==='0'?'selected':''?>>Não</option></select></div></div>
   <div class="form-row"><div class="form-group col-6"><label>Objeto *</label><input name="objeto" required value="<?=h($a['objeto'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-3"><label>Navegação</label><input name="tipo_navegacao" value="<?=h($a['tipo_navegacao'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-3"><label>Nº do casco</label><input name="numero_casco" value="<?=h($a['numero_casco'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div></div>
   <div class="form-row"><div class="form-group col-4"><label>Estaleiro</label><input name="estaleiro" value="<?=h($a['estaleiro'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-4"><label>Responsável pelo projeto</label><input name="responsavel_projeto_nome" value="<?=h($a['responsavel_projeto_nome'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-2"><label>Registro/CREA</label><input name="responsavel_projeto_registro" value="<?=h($a['responsavel_projeto_registro'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div><div class="form-group col-2"><label>ART</label><input name="art_numero" value="<?=h($a['art_numero'])?>" <?=$tecnicoEditavel?'':'disabled'?>></div></div>
   <div class="form-group"><label>Observações</label><textarea name="observacoes" rows="3" <?=$tecnicoEditavel?'':'disabled'?>><?=h($a['observacoes'])?></textarea></div>
   <?php if($tecnicoEditavel):?><div class="form-actions"><button class="btn btn-primary"><i class="fas fa-save"></i> Salvar enquadramento e checklist</button></div><?php endif?>
  </form>
 </section>

 <section class="analise-card"><h3><i class="fas fa-cloud-arrow-up"></i> Revisões e arquivos</h3>
  <?php if($analiseAberta):?><form method="post" enctype="multipart/form-data" action="<?=APP_URL?>analises-planos/actions" class="analise-inline-form"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="adicionar_submissao"><input type="hidden" name="analise_id" value="<?=h($id)?>"><select name="categoria"><?php foreach(analisePlanosCategoriasPadrao() as $cat):?><option><?=h($cat)?></option><?php endforeach?></select><input type="date" name="recebido_em" value="<?=date('Y-m-d')?>" required><input name="descricao" placeholder="Descrição da revisão"><input type="file" name="arquivos[]" multiple required accept=".pdf,.jpg,.jpeg,.png,.dwg,.dxf,.doc,.docx,.xls,.xlsx"><button class="btn btn-primary"><i class="fas fa-upload"></i> Adicionar revisão</button></form><?php endif?>
  <?php if(!$submissoes):?><p class="text-muted">Nenhuma revisão recebida.</p><?php endif;foreach($submissoes as $s):?><div class="revision-block"><strong>Revisão <?=$s['revisao']?> · <?=h($s['origem'])?></strong><span><?=formatarData($s['recebido_em'])?> · <?=h($s['usuario_nome']?:$s['portal_nome']?:'Origem não informada')?></span><?php foreach($s['arquivos'] as $arq):?><div class="file-review"><a class="file-pill" href="<?=APP_URL?>analises-planos/arquivo?id=<?=urlencode($arq['id'])?>" target="_blank"><i class="fas fa-file"></i><?=h($arq['nome_original'])?></a><span class="badge"><?=h($arq['classificacao'])?></span><?php if($analiseAberta):?><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="classificar_arquivo"><input type="hidden" name="analise_id" value="<?=h($id)?>"><input type="hidden" name="arquivo_id" value="<?=h($arq['id'])?>"><select name="item_id"><option value="">Sem item</option><?php foreach($itens as $item):?><option value="<?=h($item['id'])?>" <?=$arq['item_id']===$item['id']?'selected':''?>><?=h($item['documento'])?></option><?php endforeach?></select><select name="classificacao"><?php foreach(['ACEITO','SUBSTITUIDO','REJEITADO'] as $cl):?><option <?=$arq['classificacao']===$cl?'selected':''?>><?=$cl?></option><?php endforeach?></select><input name="justificativa" value="<?=h($arq['justificativa_classificacao'])?>" placeholder="Justificativa obrigatória para rejeitar/substituir"><button class="btn btn-secondary btn-sm">Classificar</button></form><?php endif?></div><?php endforeach?></div><?php endforeach?>
 </section>

 <section class="analise-card"><h3><i class="fas fa-list-check"></i> Matriz normativa</h3>
  <?php if(!$itens):?><p>Defina e salve o processo e a norma para gerar o checklist.</p><?php else:?><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar_itens"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="portal-table-wrap"><table><thead><tr><th>#</th><th>Documento/requisito</th><th>Referência</th><th>Obrigatório</th><th>Resultado</th><th>Observação</th></tr></thead><tbody><?php foreach($itens as $i=>$item):?><tr><td><?=$i+1?><input type="hidden" name="item_id[]" value="<?=h($item['id'])?>"></td><td><?=h($item['documento'])?></td><td><?=h($item['referencia_normativa'])?></td><td><?=$item['obrigatorio']?'Sim':'Condicional'?></td><td><select name="resultado[]" <?=$analiseAberta?'':'disabled'?>><?php foreach(['PENDENTE','CONFORME','EXIGENCIA','NAO_APLICA'] as $v):?><option value="<?=$v?>" <?=$item['resultado']===$v?'selected':''?>><?=str_replace('_',' ',$v)?></option><?php endforeach?></select></td><td><textarea name="item_observacao[]" rows="2" <?=$analiseAberta?'':'disabled'?>><?=h($item['observacao'])?></textarea></td></tr><?php endforeach?></tbody></table></div><?php if($analiseAberta):?><button class="btn btn-primary"><i class="fas fa-save"></i> Salvar matriz</button><?php endif?></form><?php endif?>
 </section>

 <section class="analise-card"><h3><i class="fas fa-triangle-exclamation"></i> Exigências vigentes</h3><p class="text-muted">A situação não é editada manualmente. A baixa somente ocorre após relatório assinado pelo analista e validado pelo admin.</p><form method="post" action="<?=APP_URL?>analises-planos/actions"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="salvar_exigencias"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="portal-table-wrap"><table><thead><tr><th>#</th><th>Descrição</th><th>Referência normativa</th><th>Situação vigente</th></tr></thead><tbody><?php foreach($exigencias as $i=>$ex):?><tr><td><?=$i+1?><input type="hidden" name="exigencia_id[]" value="<?=h($ex['id'])?>"></td><td><textarea name="exigencia_descricao[]" <?=$analiseAberta?'':'disabled'?>><?=h($ex['descricao'])?></textarea></td><td><input name="exigencia_referencia[]" value="<?=h($ex['referencia_normativa'])?>" <?=$analiseAberta?'':'disabled'?>></td><td><span class="badge"><?=h($ex['status'])?></span><?php if(!empty($ex['saneamento_pendente'])):?><small class="text-warning">Baixa histórica sem evidência: requer saneamento.</small><?php endif?></td></tr><?php endforeach?></tbody></table></div><?php if($analiseAberta):?><div class="analise-inline-form"><textarea name="nova_exigencia" placeholder="Nova exigência"></textarea><input name="nova_exigencia_referencia" placeholder="Referência normativa"><button class="btn btn-primary">Salvar cadastro de exigências</button></div><?php endif?></form></section>

 <section class="analise-card" id="pareceres"><h3><i class="fas fa-file-signature"></i> Relatórios por ciclo e licença</h3>
  <?php if($analiseAberta):?><form method="post" action="<?=APP_URL?>analises-planos/actions" class="form-padrao"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="criar_parecer"><input type="hidden" name="analise_id" value="<?=h($id)?>"><div class="form-row"><div class="form-group col-4"><label>Resultado do ciclo</label><select name="resultado"><option value="EXIGENCIAS">Exigências pendentes</option><option value="APROVADO">Conclusivo — saldo zero</option><option value="REPROVADO">Reprovado</option></select></div><div class="form-group col-4"><label>Revisão analisada *</label><select name="submissao_id" required><option value="">Selecione</option><?php foreach($submissoes as $s):?><option value="<?=h($s['id'])?>">Revisão <?=$s['revisao']?> · <?=formatarData($s['recebido_em'])?></option><?php endforeach?></select></div><div class="form-group col-4"><label>Resumo</label><textarea name="resumo" required></textarea></div></div><?php if($exigencias):?><h4>Manifestação e baixa das exigências</h4><div class="portal-table-wrap"><table><thead><tr><th>Exigência</th><th>Resultado deste ciclo</th><th>Manifestação técnica</th></tr></thead><tbody><?php foreach($exigencias as $ex):?><tr><td><?=h($ex['descricao'])?></td><td><select name="baixa_resultado[<?=h($ex['id'])?>]" required><option value="NAO_CUMPRIDA">Não cumprida</option><option value="PARCIAL">Parcial</option><option value="CUMPRIDA">Cumprida</option></select></td><td><textarea name="baixa_manifestacao[<?=h($ex['id'])?>]" required placeholder="Indique a evidência e a conclusão técnica"></textarea></td></tr><?php endforeach?></tbody></table></div><?php endif?><div class="form-group"><label>Conclusão</label><textarea name="conclusao" required></textarea></div><button class="btn btn-primary"><i class="fas fa-paper-plane"></i> Preparar relatório do ciclo</button></form><?php endif?>
  <?php foreach($pareceres as $p):?><article class="parecer-row"><div><strong><?=h($p['numero']?:('Relatório histórico v'.$p['versao']))?> · <?=h($p['finalidade']?:$p['resultado'])?></strong><span><?=h($p['status'])?> · <?=formatarDataCompleta($p['criado_em'])?></span><?php if($p['devolvido_motivo']):?><small><?=h($p['devolvido_motivo'])?></small><?php endif?></div><div><a class="btn btn-secondary btn-sm" target="_blank" href="<?=APP_URL?>analises-planos/parecer-pdf?id=<?=urlencode($p['id'])?>"><i class="fas fa-eye"></i> PDF</a><?php if($p['status']==='AGUARDANDO_ASSINATURA_ANALISTA'&&$cargo==='ANALISTA'&&$p['criado_por']===$usuario):?><form method="post" action="<?=APP_URL?>analises-planos/actions" style="display:inline"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="assinar_parecer"><input type="hidden" name="analise_id" value="<?=h($id)?>"><input type="hidden" name="parecer_id" value="<?=h($p['id'])?>"><button class="btn btn-success btn-sm"><i class="fas fa-signature"></i> Assinar tecnicamente</button></form><?php endif?><?php if($p['status']==='AGUARDANDO_APROVACAO_ADMIN'&&$cargo==='ADMIN'):?><form method="post" action="<?=APP_URL?>analises-planos/actions" style="display:inline"><input type="hidden" name="csrf_token" value="<?=gerarCSRF()?>"><input type="hidden" name="action" value="publicar"><input type="hidden" name="analise_id" value="<?=h($id)?>"><input type="hidden" name="parecer_id" value="<?=h($p['id'])?>"><button class="btn btn-success btn-sm">Validar e publicar</button><input name="motivo" placeholder="Motivo se devolver"><button name="devolver" value="1" class="btn btn-warning btn-sm">Devolver</button></form><?php endif?></div></article><?php endforeach?>
  <?php if($licenca):?><div class="alert alert-success"><strong>Licença <?=h($licenca['numero_lc'])?></strong> · <?=h($licenca['tipo_licenca'])?> · <?=h($licenca['status'])?> <a href="<?=APP_URL?>documentacao/lc/form?id=<?=urlencode($licenca['id'])?>">Abrir licença</a></div><?php endif?>
 </section>

 <section class="analise-card"><h3><i class="fas fa-clock-rotate-left"></i> Histórico auditável</h3><div class="timeline"><?php foreach($historico as $h):?><div><strong><?=h($h['evento'])?></strong><span><?=h($h['usuario_nome'])?> · <?=formatarDataCompleta($h['criado_em'])?></span><?php if($h['detalhe']):?><p><?=h($h['detalhe'])?></p><?php endif?></div><?php endforeach?></div></section>
</div>
<style>.analise-planos-page{display:grid;gap:18px}.analise-card{background:var(--cor-card,#fff);border:1px solid var(--cor-borda,#ddd);border-radius:12px;padding:20px}.analise-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;padding:14px 20px}.analise-summary span{display:flex;flex-direction:column;gap:4px}.analise-inline-form{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.analise-inline-form>*{flex:1;min-width:150px}.revision-block{padding:14px 0;border-top:1px solid var(--cor-borda,#ddd)}.revision-block>span{margin-left:10px}.file-review{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}.file-review form{display:flex;gap:7px;flex:1}.file-pill{padding:8px;border:1px solid var(--cor-borda,#ddd);border-radius:8px}.parecer-row{display:flex;justify-content:space-between;align-items:center;padding:14px 0;border-top:1px solid var(--cor-borda,#ddd)}.parecer-row>div:first-child{display:flex;flex-direction:column;gap:5px}.timeline>div{border-left:3px solid #2596be;padding:2px 0 14px 14px}.timeline span{display:block;font-size:.85rem;opacity:.7}.timeline p{margin:5px 0}@media(max-width:900px){.analise-summary{grid-template-columns:1fr 1fr}.parecer-row{align-items:flex-start;flex-direction:column}.file-review form{min-width:100%;flex-wrap:wrap}}</style>
<?php require_once __DIR__ . '/../../includes/footer.php';?>
