<?php
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/financeiro_relatorio.php';

verificar_sessao();
exigirAcesso('financeiro');

try {
    $relatorio = financeiroRelatorioDados($pdo, $_GET['mes'] ?? date('Y-m'), $_GET['escritorio_id'] ?? null);
} catch (Throwable $e) {
    setMensagem('error', $e->getMessage());
    redirecionar(APP_URL . 'financeiro/relatorios');
}
extract($relatorio);
$exportQuery=http_build_query(['mes'=>$mes,'escritorio_id'=>$filtro_escritorio]);
$titulo_page='Relatórios Financeiros - ERP Sistema';
require_once __DIR__ . '/../../includes/header.php';
require_once __DIR__ . '/../../includes/sidebar.php';
?>
<style>
.finance-report-head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;flex-wrap:wrap}.finance-report-actions{display:flex;gap:8px;flex-wrap:wrap}.finance-scope{display:inline-flex;align-items:center;gap:7px;margin-top:7px;padding:6px 10px;border-radius:999px;background:#eaf7f1;color:#08734d;font-size:12px;font-weight:700}.finance-kpis{display:grid;grid-template-columns:repeat(4,minmax(170px,1fr));gap:14px;margin:20px 0}.finance-kpi{padding:18px;border:1px solid var(--cor-borda);border-radius:12px;background:var(--cor-card)}.finance-kpi span{display:block;color:var(--cor-texto-secundario);font-size:12px}.finance-kpi strong{display:block;margin-top:8px;font-size:22px}.finance-kpi.is-positive strong{color:#15905d}.finance-kpi.is-danger strong{color:#c0392b}.performance-cards{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:20px}.performance-card{display:flex;align-items:center;gap:14px;padding:18px;border:1px solid var(--cor-borda);border-left:4px solid #15905d;border-radius:12px;background:var(--cor-card)}.performance-card.is-attention{border-left-color:#e39b22}.performance-card i{font-size:25px}.performance-card span{display:block;color:var(--cor-texto-secundario);font-size:11px;text-transform:uppercase;font-weight:800}.performance-card strong{display:block;margin:3px 0}.report-filter{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.report-filter label{display:grid;gap:4px;font-size:11px;font-weight:700}.report-filter select,.report-filter input{min-width:190px}.report-section{margin-top:18px}.report-table-wrap{overflow:auto}.finance-report-table{width:100%}.rank-good{color:#15905d}.rank-attention{color:#c07b0a}@media(max-width:900px){.finance-kpis{grid-template-columns:repeat(2,1fr)}.performance-cards{grid-template-columns:1fr}}@media(max-width:768px){.finance-report-actions{width:100%}.finance-report-actions .btn{flex:1;justify-content:center;min-height:44px}.report-filter{display:grid;grid-template-columns:1fr}.report-filter label,.report-filter select,.report-filter input,.report-filter .btn{width:100%;min-width:0;box-sizing:border-box}.report-filter select,.report-filter input,.report-filter .btn{min-height:44px}.report-table-wrap{overflow:visible!important}.report-table-wrap .finance-report-table{min-width:0!important}.performance-card{align-items:flex-start}.performance-card i{margin-top:3px}}@media(max-width:520px){.finance-kpis{grid-template-columns:1fr}.finance-report-head{gap:12px}.finance-report-actions{display:grid;grid-template-columns:1fr}.performance-card{padding:15px}}
</style>
<main class="main-content">
    <header class="page-header finance-report-head">
        <div><h1 class="page-title">Relatório Financeiro</h1><p class="page-subtitle">Visão consolidada ou detalhada por escritório</p><span class="finance-scope"><i class="fa-solid fa-building"></i><?= h($escopo_nome) ?> · <?= h(date('m/Y',strtotime($inicio))) ?></span></div>
        <div class="finance-report-actions"><a class="btn btn-danger" href="<?= APP_URL ?>financeiro/relatorios/exportar?formato=pdf&amp;<?= h($exportQuery) ?>"><i class="fa-solid fa-file-pdf"></i> Exportar PDF</a><a class="btn btn-success" href="<?= APP_URL ?>financeiro/relatorios/exportar?formato=xlsx&amp;<?= h($exportQuery) ?>"><i class="fa-solid fa-file-excel"></i> Exportar Excel</a></div>
    </header>

    <section class="card"><div class="card-body"><form method="get" class="report-filter"><label>Escritório<select name="escritorio_id" <?= $pode_selecionar?'':'disabled' ?>><?php if(financeiroEhAdmin()): ?><option value="todos" <?= $filtro_escritorio==='todos'?'selected':'' ?>>Todos os escritórios</option><?php endif ?><?php foreach($escritorios as $e): ?><option value="<?= h($e['id']) ?>" <?= $filtro_escritorio===$e['id']?'selected':'' ?>><?= h($e['nome'].' · '.$e['cidade'].'/'.$e['uf']) ?></option><?php endforeach ?></select></label><?php if(!$pode_selecionar): ?><input type="hidden" name="escritorio_id" value="<?= h($filtro_escritorio) ?>"><?php endif ?><label>Competência<input type="month" name="mes" value="<?= h($mes) ?>"></label><button class="btn btn-primary"><i class="fa-solid fa-filter"></i> Aplicar filtro</button></form></div></section>

    <?php $saldoRealizado=$fluxo['receita_realizada']-$fluxo['despesa_realizada']; ?>
    <section class="finance-kpis">
        <article class="finance-kpi is-positive"><span>Recebido no período</span><strong><?= formatarMoeda($kpis['recebido']) ?></strong></article>
        <article class="finance-kpi"><span>A receber no período</span><strong><?= formatarMoeda($kpis['a_receber']) ?></strong></article>
        <article class="finance-kpi is-danger"><span>Inadimplência atual</span><strong><?= formatarMoeda($kpis['inadimplente']) ?></strong></article>
        <article class="finance-kpi <?= $saldoRealizado>=0?'is-positive':'is-danger' ?>"><span>Saldo realizado</span><strong><?= formatarMoeda($saldoRealizado) ?></strong></article>
    </section>

    <section class="performance-cards">
        <article class="performance-card"><i class="fa-solid fa-trophy"></i><div><span>Maior desempenho no período</span><strong><?= h($melhor['nome']??'Sem dados') ?></strong><small><?= $melhor?formatarMoeda($melhor['recebido']).' recebidos · '.(int)$melhor['vendas_qtd'].' venda(s)':'Nenhum vendedor encontrado' ?></small></div></article>
        <article class="performance-card is-attention"><i class="fa-solid fa-arrow-trend-down"></i><div><span>Menor desempenho no período</span><strong><?= h($menor['nome']??'Sem dados') ?></strong><small><?= $menor?formatarMoeda($menor['recebido']).' recebidos · '.formatarMoeda($menor['vencido']).' inadimplentes':'Nenhum vendedor encontrado' ?></small></div></article>
    </section>

    <section class="card report-section"><div class="card-header"><h3><i class="fa-solid fa-building"></i> Resultado por escritório</h3></div><div class="card-body report-table-wrap"><table class="data-table finance-report-table"><thead><tr><th>#</th><th>Escritório</th><th>Recebido</th><th>Despesas</th><th>Saldo</th><th>A receber (geral)</th><th>Meta</th><th>Atingimento</th></tr></thead><tbody><?php foreach($comparativo as $i=>$e): ?><tr><td><?= $i+1 ?></td><td><strong><?= h($e['nome']) ?></strong><br><small><?= h($e['cidade'].'/'.$e['uf']) ?></small></td><td class="text-right text-success"><?= formatarMoeda($e['recebido']) ?></td><td class="text-right text-danger"><?= formatarMoeda($e['despesas']) ?></td><td class="text-right"><strong><?= formatarMoeda($e['saldo']) ?></strong></td><td class="text-right"><?= formatarMoeda($e['aberto']) ?></td><td class="text-right"><?= formatarMoeda($e['meta']) ?></td><td><span class="badge <?= $e['meta']>0&&$e['atingimento']>=100?'badge-success':'badge-warning' ?>"><?= number_format($e['atingimento'],1,',','.') ?>%</span></td></tr><?php endforeach ?><?php if(!$comparativo): ?><tr><td colspan="8">Nenhum escritório disponível.</td></tr><?php endif ?></tbody></table></div></section>

    <section class="card report-section"><div class="card-header"><h3><i class="fa-solid fa-ranking-star"></i> Ranking completo dos vendedores</h3></div><div class="card-body report-table-wrap"><table class="data-table" style="min-width:1050px"><thead><tr><th>Posição</th><th>Vendedor</th><th>Recebido</th><th>Vendas assinadas</th><th>Ticket médio</th><th>A receber</th><th>Inadimplente</th><th>Variação mensal</th></tr></thead><tbody><?php foreach($ranking as $i=>$v): ?><tr><td><strong class="<?= $i===0?'rank-good':($i===count($ranking)-1?'rank-attention':'') ?>"><?= $i+1 ?>º</strong></td><td><strong><?= h($v['nome']) ?></strong><br><small><?= h($v['escritorio_nome']) ?></small></td><td class="text-right text-success"><strong><?= formatarMoeda($v['recebido']) ?></strong></td><td><?= (int)$v['vendas_qtd'] ?><br><small><?= formatarMoeda($v['vendas_valor']) ?></small></td><td class="text-right"><?= formatarMoeda($v['ticket']) ?></td><td class="text-right"><?= formatarMoeda($v['aberto']) ?></td><td class="text-right text-danger"><?= formatarMoeda($v['vencido']) ?></td><td><span class="badge <?= $v['variacao']>=0?'badge-success':'badge-danger' ?>"><?= $v['variacao']>=0?'+':'' ?><?= number_format($v['variacao'],1,',','.') ?>%</span></td></tr><?php endforeach ?><?php if(!$ranking): ?><tr><td colspan="8">Nenhum vendedor ou movimento no período.</td></tr><?php endif ?></tbody></table></div></section>

    <div class="grid-2 report-section">
        <section class="card"><div class="card-header"><h3><i class="fa-solid fa-money-bill-transfer"></i> Fluxo de caixa</h3></div><div class="card-body"><table class="data-table"><thead><tr><th>Indicador</th><th>Previsto</th><th>Realizado</th></tr></thead><tbody><tr><td>Receitas</td><td><?= formatarMoeda($fluxo['receita_prevista']) ?></td><td class="text-success"><?= formatarMoeda($fluxo['receita_realizada']) ?></td></tr><tr><td>Despesas</td><td><?= formatarMoeda($fluxo['despesa_prevista']) ?></td><td class="text-danger"><?= formatarMoeda($fluxo['despesa_realizada']) ?></td></tr><tr><td><strong>Saldo</strong></td><td><strong><?= formatarMoeda($fluxo['receita_prevista']-$fluxo['despesa_prevista']) ?></strong></td><td><strong><?= formatarMoeda($saldoRealizado) ?></strong></td></tr></tbody></table></div></section>
        <section class="card"><div class="card-header"><h3><i class="fa-solid fa-chart-column"></i> Evolução - 6 meses</h3></div><div class="card-body report-table-wrap"><table class="data-table"><thead><tr><th>Mês</th><th>Receitas</th><th>Despesas</th><th>Saldo</th></tr></thead><tbody><?php foreach($evolucao['labels'] as $i=>$label): ?><tr><td><?= h($label) ?></td><td class="text-success"><?= formatarMoeda($evolucao['receitas'][$i]) ?></td><td class="text-danger"><?= formatarMoeda($evolucao['despesas'][$i]) ?></td><td><?= formatarMoeda($evolucao['receitas'][$i]-$evolucao['despesas'][$i]) ?></td></tr><?php endforeach ?></tbody></table></div></section>
    </div>

    <section class="card report-section"><div class="card-header"><h3><i class="fa-solid fa-file-invoice-dollar"></i> Contas a receber prioritárias</h3></div><div class="card-body report-table-wrap"><table class="data-table" style="min-width:850px"><thead><tr><th>Cliente / lançamento</th><th>Escritório</th><th>Vendedor</th><th>Vencimento</th><th>Situação</th><th>Saldo</th><th></th></tr></thead><tbody><?php foreach($cobrancas as $c): $atrasada=(int)$c['dias_atraso']>0; ?><tr><td><strong><?= h($c['cliente']) ?></strong><br><small><?= h(mb_strimwidth($c['descricao'],0,55,'...')) ?></small></td><td><?= h($c['escritorio']) ?></td><td><?= h($c['vendedor']?:'-') ?></td><td><?= formatarData($c['data_vencimento']) ?></td><td><span class="badge <?= $atrasada?'badge-danger':'badge-warning' ?>"><?= $atrasada?(int)$c['dias_atraso'].' dia(s) em atraso':($c['status']==='PARCIAL'?'Parcial':'A vencer') ?></span></td><td class="text-right"><strong><?= formatarMoeda($c['saldo_devedor']) ?></strong></td><td><a class="btn btn-secondary btn-sm" href="<?= APP_URL ?>financeiro/form?id=<?= urlencode($c['id']) ?>"><i class="fas fa-arrow-right"></i></a></td></tr><?php endforeach ?><?php if(!$cobrancas): ?><tr><td colspan="7">Nenhuma conta pendente neste filtro.</td></tr><?php endif ?></tbody></table></div></section>
</main>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
