<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/protocolos.php';
$token=trim($_GET['token']??'');$hash=hash('sha256',$token);
$q=$pdo->prepare("SELECT a.*,m.dossie_id,m.sequencia,m.tipo,m.natureza,m.origem_nome,m.destino_nome,m.movimentado_em,d.numero,d.assunto,e.nome embarcacao_nome
FROM protocolo_aceites a JOIN protocolo_movimentacoes m ON m.id=a.movimentacao_id JOIN protocolo_dossies d ON d.id=m.dossie_id JOIN embarcacoes e ON e.id=d.embarcacao_id WHERE a.token_hash=:hash");
$q->execute([':hash'=>$hash]);$a=$q->fetch(PDO::FETCH_ASSOC);$erro='';
if(!$a)$erro='Link de aceite inválido.';elseif($a['aceito_em'])$erro='Este recebimento já foi confirmado em '.date('d/m/Y H:i',strtotime($a['aceito_em'])).'.';elseif(strtotime($a['expira_em'])<time())$erro='Este link de aceite expirou.';
if($_SERVER['REQUEST_METHOD']==='POST'&&!$erro){
 if(!verificarCSRF($_POST['csrf_token']??''))$erro='Sessão expirada. Atualize a página.';
 elseif(empty($_POST['termo']))$erro='Confirme o recebimento para continuar.';
 else{$nome=trim($_POST['nome']??'');$doc=trim($_POST['documento']??'');if(!$nome||strlen(preg_replace('/\D+/','',$doc))<5)$erro='Informe nome e documento válidos.';else{
  $pdo->beginTransaction();$u=$pdo->prepare('UPDATE protocolo_aceites SET nome=:nome,documento_mascarado=:doc,termo_aceito=1,ip=:ip,aceito_em=NOW() WHERE id=:id AND aceito_em IS NULL AND expira_em>=NOW()');$u->execute([':nome'=>$nome,':doc'=>protocoloMascararDocumento($doc),':ip'=>obterIpCliente(),':id'=>$a['id']]);if($u->rowCount()!==1){$pdo->rollBack();$erro='O aceite não está mais disponível.';}else{if($a['natureza']==='ENTREGA_CLIENTE')$pdo->prepare("UPDATE protocolo_dossies SET status='ENTREGUE_AO_CLIENTE' WHERE id=:id AND status NOT IN('ENCERRADO','CANCELADO')")->execute([':id'=>$a['dossie_id']]);protocoloAuditar($pdo,$a['dossie_id'],$a['movimentacao_id'],'ACEITE_DIGITAL',null,'ACEITO','Recebimento confirmado por '.$nome);$pdo->commit();$a['aceito_em']=date('Y-m-d H:i:s');}}
 }
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aceite de protocolo</title><style>body{font-family:Arial,sans-serif;background:#eef5f2;color:#173b32;margin:0;padding:24px}.box{max-width:650px;margin:40px auto;background:#fff;border-radius:16px;padding:28px;box-shadow:0 8px 30px #173b3220}.brand{color:#087653;font-weight:800}.meta{background:#f1f8f5;border-radius:10px;padding:15px;line-height:1.6}.field{margin:15px 0}.field label{display:block;font-weight:700;margin-bottom:6px}.field input[type=text]{width:100%;box-sizing:border-box;padding:12px;border:1px solid #bdcec7;border-radius:8px}.btn{background:#07825b;color:#fff;border:0;padding:12px 18px;border-radius:9px;font-weight:700;cursor:pointer}.error{background:#ffeded;color:#8b2020;padding:12px;border-radius:8px}.ok{background:#e4f8ef;color:#076c4c;padding:18px;border-radius:8px}</style></head><body><main class="box"><div class="brand">AMAZON NAVAL</div><h1>Confirmação de recebimento</h1>
<?php if(!$a): ?><div class="error"><?= h($erro) ?></div><?php elseif($a['aceito_em']): ?><div class="ok"><strong>Recebimento confirmado.</strong><br>Este aceite ficou registrado com data, identificação mascarada e endereço IP para auditoria.</div><div class="meta"><b><?= h($a['numero']) ?> · Evento <?= str_pad((string)$a['sequencia'],2,'0',STR_PAD_LEFT) ?></b><br><?= h($a['embarcacao_nome']) ?><br><?= h($a['assunto']) ?></div>
<?php elseif($erro): ?><div class="error"><?= h($erro) ?></div>
<?php else: ?><?php if($erro): ?><div class="error"><?= h($erro) ?></div><?php endif; ?><div class="meta"><b><?= h($a['numero']) ?> · Evento <?= str_pad((string)$a['sequencia'],2,'0',STR_PAD_LEFT) ?></b><br>Embarcação: <?= h($a['embarcacao_nome']) ?><br><?= h($a['origem_nome']) ?> → <?= h($a['destino_nome']) ?><br>Movimentado em <?= date('d/m/Y H:i',strtotime($a['movimentado_em'])) ?></div>
<form method="post"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><div class="field"><label>Nome completo *</label><input type="text" required name="nome"></div><div class="field"><label>CPF ou documento *</label><input type="text" required name="documento" autocomplete="off"><small>O sistema armazenará apenas uma versão mascarada.</small></div><div class="field"><label><input type="checkbox" name="termo" value="1" required> Confirmo que recebi os documentos descritos no comprovante desta movimentação.</label></div><button class="btn">Confirmar recebimento</button></form><?php endif; ?></main></body></html>
