<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/protocolos.php';protocoloExigirAcesso();
if(getCargo()!=='ADMIN'){setMensagem('error','Somente o administrador gerencia unidades e catálogo.');redirecionar(APP_URL.'protocolos');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verificarCSRF($_POST['csrf_token']??'')){setMensagem('error','Sessão expirada.');redirecionar(APP_URL.'protocolos/configuracoes');}
 try{$a=trim($_POST['action']??'');
  if($a==='unidade'){$id=trim($_POST['id']??'')?:gerarUUID();$tipo=trim($_POST['tipo']??'');if(!in_array($tipo,['CAPITANIA','DELEGACIA','AGENCIA'],true))throw new RuntimeException('Tipo inválido.');$nome=trim($_POST['nome']??'');$cidade=trim($_POST['cidade']??'');$uf=strtoupper(trim($_POST['uf']??''));if(!$nome||!$cidade||!preg_match('/^[A-Z]{2}$/',$uf))throw new RuntimeException('Informe nome, cidade e UF.');$regex=trim($_POST['formato_protocolo_regex']??'')?:null;if($regex&&@preg_match($regex,'')===false)throw new RuntimeException('Expressão de validação inválida.');$q=$pdo->prepare("INSERT INTO protocolo_unidades_maritimas(id,codigo,nome,tipo,cidade,uf,endereco,telefone,email,jurisdicao,formato_protocolo_regex,url_consulta,ativo,criado_por)VALUES(:id,:codigo,:nome,:tipo,:cidade,:uf,:endereco,:telefone,:email,:jurisdicao,:regex,:url,1,:usuario) ON DUPLICATE KEY UPDATE codigo=VALUES(codigo),nome=VALUES(nome),tipo=VALUES(tipo),cidade=VALUES(cidade),uf=VALUES(uf),endereco=VALUES(endereco),telefone=VALUES(telefone),email=VALUES(email),jurisdicao=VALUES(jurisdicao),formato_protocolo_regex=VALUES(formato_protocolo_regex),url_consulta=VALUES(url_consulta),ativo=1");$q->execute([':id'=>$id,':codigo'=>trim($_POST['codigo']??'')?:null,':nome'=>$nome,':tipo'=>$tipo,':cidade'=>$cidade,':uf'=>$uf,':endereco'=>trim($_POST['endereco']??'')?:null,':telefone'=>trim($_POST['telefone']??'')?:null,':email'=>trim($_POST['email']??'')?:null,':jurisdicao'=>trim($_POST['jurisdicao']??'')?:null,':regex'=>$regex,':url'=>trim($_POST['url_consulta']??'')?:null,':usuario'=>$_SESSION['usuario_id']]);}
  elseif($a==='catalogo'){$codigo=strtoupper(trim($_POST['codigo']??''));$nome=trim($_POST['nome']??'');$cat=trim($_POST['categoria']??'OUTROS');$cats=['ANALISE_PLANOS','VISTORIA','INSCRICAO','CERTIFICADOS','PROPRIEDADE','RESPONSABILIDADE_TECNICA','DOCUMENTOS_PESSOAIS','OUTROS'];if(!$codigo||!preg_match('/^[A-Z0-9_]+$/',$codigo)||!$nome||!in_array($cat,$cats,true))throw new RuntimeException('Informe código estável, categoria e nome.');$q=$pdo->prepare('INSERT INTO protocolo_catalogo_documentos(id,codigo,categoria,nome,contexto,norma_referencia,ativo,ordem)VALUES(UUID(),:codigo,:cat,:nome,:contexto,:norma,1,:ordem) ON DUPLICATE KEY UPDATE categoria=VALUES(categoria),nome=VALUES(nome),contexto=VALUES(contexto),norma_referencia=VALUES(norma_referencia),ativo=1,ordem=VALUES(ordem)');$q->execute([':codigo'=>$codigo,':cat'=>$cat,':nome'=>$nome,':contexto'=>trim($_POST['contexto']??'')?:null,':norma'=>trim($_POST['norma_referencia']??'')?:null,':ordem'=>(int)($_POST['ordem']??0)]);}
  elseif($a==='alertas'){$q=$pdo->prepare('UPDATE protocolo_configuracoes SET valor=:valor,atualizado_por=:usuario WHERE chave=:chave');foreach(['dias_sem_comprovante','dias_sem_protocolo_oficial','dias_alerta_validade'] as $chave){$valor=max(1,min(365,(int)($_POST[$chave]??0)));$q->execute([':valor'=>(string)$valor,':usuario'=>$_SESSION['usuario_id'],':chave'=>$chave]);}}
  else throw new RuntimeException('Ação inválida.');
  setMensagem('success','Cadastro atualizado.');
 }catch(Throwable $e){setMensagem('error',$e->getMessage());}
 redirecionar(APP_URL.'protocolos/configuracoes');
}
$unidades=$pdo->query('SELECT * FROM protocolo_unidades_maritimas ORDER BY ativo DESC,tipo,nome')->fetchAll(PDO::FETCH_ASSOC);$docs=$pdo->query('SELECT * FROM protocolo_catalogo_documentos ORDER BY categoria,ordem,nome')->fetchAll(PDO::FETCH_ASSOC);try{$alertas=$pdo->query('SELECT chave,valor FROM protocolo_configuracoes')->fetchAll(PDO::FETCH_KEY_PAIR);}catch(Throwable $e){$alertas=[];}
$titulo_page='Configurações de protocolos';require __DIR__.'/../../includes/header.php';require __DIR__.'/../../includes/sidebar.php';
?><main class="conteudo-principal"><div style="display:flex;justify-content:space-between;gap:12px"><div><h1>Cadastros de protocolo</h1><p>Unidades marítimas e catálogo sugerido de documentos.</p></div><a class="btn btn-secondary" href="<?= APP_URL ?>protocolos">Voltar</a></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><section class="card"><div class="card-body"><h2>Unidade marítima</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="unidade"><div class="form-group"><label>Código</label><input class="form-control" name="codigo"></div><div class="form-group"><label>Nome *</label><input class="form-control" name="nome" required></div><div class="form-group"><label>Tipo *</label><select class="form-control" name="tipo"><option>CAPITANIA</option><option>DELEGACIA</option><option>AGENCIA</option></select></div><div style="display:grid;grid-template-columns:2fr 1fr;gap:8px"><input class="form-control" name="cidade" required placeholder="Cidade"><input class="form-control" name="uf" required maxlength="2" placeholder="UF"></div><input class="form-control" name="endereco" placeholder="Endereço"><input class="form-control" name="telefone" placeholder="Telefone"><input class="form-control" name="email" type="email" placeholder="E-mail"><textarea class="form-control" name="jurisdicao" placeholder="Jurisdição"></textarea><input class="form-control" name="formato_protocolo_regex" placeholder="Regex opcional, ex.: /^\\d+$/"><input class="form-control" name="url_consulta" type="url" placeholder="Link oficial de consulta"><button class="btn btn-primary" style="margin-top:10px">Salvar unidade</button></form><hr><?php foreach($unidades as $u): ?><p><strong><?= h($u['nome']) ?></strong><br><small><?= h($u['tipo'].' · '.$u['cidade'].'/'.$u['uf']) ?></small></p><?php endforeach; ?></div></section>
<section class="card"><div class="card-body"><h2>Alertas</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="alertas"><label>Dias sem comprovante de entrega</label><input class="form-control" type="number" min="1" max="365" name="dias_sem_comprovante" value="<?= h($alertas['dias_sem_comprovante']??3) ?>"><label>Dias sem protocolo oficial após envio</label><input class="form-control" type="number" min="1" max="365" name="dias_sem_protocolo_oficial" value="<?= h($alertas['dias_sem_protocolo_oficial']??3) ?>"><label>Antecedência da validade</label><input class="form-control" type="number" min="1" max="365" name="dias_alerta_validade" value="<?= h($alertas['dias_alerta_validade']??15) ?>"><button class="btn btn-primary" style="margin-top:10px">Salvar alertas</button></form><hr><h2>Documento do catálogo</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="catalogo"><input class="form-control" required name="codigo" placeholder="CÓDIGO_ESTÁVEL"><input class="form-control" required name="nome" placeholder="Nome do documento"><select class="form-control" name="categoria"><?php foreach(['ANALISE_PLANOS','VISTORIA','INSCRICAO','CERTIFICADOS','PROPRIEDADE','RESPONSABILIDADE_TECNICA','DOCUMENTOS_PESSOAIS','OUTROS'] as $c): ?><option><?= $c ?></option><?php endforeach; ?></select><input class="form-control" name="contexto" placeholder="Contexto/serviço"><input class="form-control" name="norma_referencia" value="NORMAM-202/DPC" placeholder="Referência normativa"><input class="form-control" type="number" name="ordem" value="0"><button class="btn btn-primary" style="margin-top:10px">Salvar documento</button></form><hr><div style="max-height:520px;overflow:auto"><?php foreach($docs as $doc): ?><p><strong><?= h($doc['nome']) ?></strong><br><small><?= h($doc['codigo'].' · '.$doc['categoria'].($doc['contexto']?' · '.$doc['contexto']:'')) ?></small></p><?php endforeach; ?></div></div></section></div></main><style>@media(max-width:800px){.conteudo-principal>div[style*="grid-template-columns"]{grid-template-columns:1fr!important}}</style><?php require __DIR__.'/../../includes/footer.php'; ?>
