<?php
require_once __DIR__.'/../../config.php';require_once __DIR__.'/../../includes/functions.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/protocolos.php';protocoloExigirAcesso();
$id=trim($_GET['id']??'');$d=null;$movs=[];$comprovantes=[];$auditoria=[];$originais=[];$preEmb=trim($_GET['embarcacao_id']??'');
$embarcacoes=$pdo->query("SELECT e.id,e.nome,e.registro,COALESCE(e.cliente_id,e.proprietario_id) cliente_id,c.nome cliente_nome FROM embarcacoes e LEFT JOIN clientes c ON c.id=COALESCE(e.cliente_id,e.proprietario_id) WHERE e.ativo=1 ORDER BY e.nome")->fetchAll(PDO::FETCH_ASSOC);
$clientes=$pdo->query('SELECT id,nome FROM clientes ORDER BY nome')->fetchAll(PDO::FETCH_ASSOC);
$unidades=$pdo->query('SELECT * FROM protocolo_unidades_maritimas WHERE ativo=1 ORDER BY tipo,nome')->fetchAll(PDO::FETCH_ASSOC);
$catalogo=$pdo->query('SELECT * FROM protocolo_catalogo_documentos WHERE ativo=1 ORDER BY categoria,ordem,nome')->fetchAll(PDO::FETCH_ASSOC);
if($id){
 $d=protocoloCarregar($pdo,$id);
 $q=$pdo->prepare("SELECT m.*,u.nome criador_nome,um.nome unidade_nome,(SELECT COUNT(*) FROM protocolo_movimentacao_itens i WHERE i.movimentacao_id=m.id) itens_total FROM protocolo_movimentacoes m LEFT JOIN usuarios u ON u.id=m.criado_por LEFT JOIN protocolo_unidades_maritimas um ON um.id=m.unidade_maritima_id WHERE m.dossie_id=:id ORDER BY m.sequencia");$q->execute([':id'=>$id]);$movs=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare('SELECT * FROM protocolo_comprovantes WHERE dossie_id=:id ORDER BY criado_em DESC');$q->execute([':id'=>$id]);$comprovantes=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare('SELECT a.*,u.nome usuario_nome FROM protocolo_auditoria a LEFT JOIN usuarios u ON u.id=a.usuario_id WHERE a.dossie_id=:id ORDER BY a.criado_em DESC LIMIT 100');$q->execute([':id'=>$id]);$auditoria=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$pdo->prepare("SELECT i.*,m.sequencia,m.status movimentacao_status FROM protocolo_movimentacao_itens i JOIN protocolo_movimentacoes m ON m.id=i.movimentacao_id WHERE m.dossie_id=:id AND i.requer_devolucao=1 ORDER BY i.devolvido_em IS NULL DESC,m.sequencia");$q->execute([':id'=>$id]);$originais=$q->fetchAll(PDO::FETCH_ASSOC);
}
$labels=protocoloRotulosStatus();$somenteLeitura=$d&&in_array($d['status'],['ENCERRADO','CANCELADO'],true);$retificar=trim($_GET['retificar']??'');
$titulo_page=($d?$d['numero']:'Novo protocolo').' - ERP';require __DIR__.'/../../includes/header.php';require __DIR__.'/../../includes/sidebar.php';
?>
<style>
.p-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.p-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.p-field label{font-weight:700;display:block;margin-bottom:6px}.p-timeline{border-left:3px solid #16a474;margin-left:15px;padding-left:24px}.p-event{position:relative;border:1px solid #dce7e2;border-radius:13px;padding:16px;margin-bottom:15px;background:#fff}.p-event:before{content:"";position:absolute;width:15px;height:15px;border-radius:50%;background:#12ae7a;left:-34px;top:20px;border:3px solid #fff}.p-event-head{display:flex;justify-content:space-between;gap:12px}.p-chip{display:inline-block;padding:4px 8px;border-radius:20px;background:#e8f7f1;color:#087654;font-size:12px;font-weight:700}.p-doc{display:grid;grid-template-columns:2.2fr 1fr 1fr .55fr 1fr auto;gap:8px;padding:10px 0;border-bottom:1px solid #e4ebe8}.p-actions{display:flex;flex-wrap:wrap;gap:8px}.p-note{padding:12px;border-radius:9px;background:#fff7df;color:#765500}.p-section{margin-top:17px}.p-hash{font-family:monospace;font-size:11px;word-break:break-all}@media(max-width:850px){.p-grid,.p-doc{grid-template-columns:1fr}.p-head,.p-event-head{flex-direction:column}.p-doc{padding:14px;border:1px solid #dce7e2;border-radius:10px;margin:9px 0}}
</style>
<main class="conteudo-principal">
 <div class="p-head"><div><h1><i class="fa-solid fa-folder-tree"></i> <?= $d?h($d['numero']):'Novo dossiê de protocolo' ?></h1><p><?= $d?h($d['assunto']):'Abra um assunto para registrar toda a entrada, saída e tramitação.' ?></p></div><a class="btn btn-secondary" href="<?= APP_URL ?>protocolos"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
 <?php if(!$d): ?>
 <section class="card"><div class="card-body"><h2>1. Identificação do dossiê</h2><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="criar">
  <div class="p-grid">
   <div class="p-field"><label>Embarcação *</label><select class="form-control" required name="embarcacao_id" id="embarcacao"><option value="">Selecione</option><?php foreach($embarcacoes as $e): ?><option value="<?= h($e['id']) ?>" data-cliente="<?= h($e['cliente_id']) ?>" <?= $preEmb===$e['id']?'selected':'' ?>><?= h($e['nome'].($e['registro']?' · '.$e['registro']:'')) ?></option><?php endforeach; ?></select></div>
   <div class="p-field"><label>Cliente</label><select class="form-control" name="cliente_id" id="cliente"><option value="">Usar vínculo da embarcação</option><?php foreach($clientes as $c): ?><option value="<?= h($c['id']) ?>"><?= h($c['nome']) ?></option><?php endforeach; ?></select></div>
   <div class="p-field" style="grid-column:1/-1"><label>Assunto *</label><input class="form-control" required maxlength="255" name="assunto" placeholder="Ex.: Apresentação do projeto para Licença de Construção"></div>
   <div class="p-field"><label>Processo de análise (opcional)</label><input class="form-control" name="analise_id" value="<?= h($_GET['analise_id']??'') ?>" placeholder="ID do processo relacionado"></div>
   <div class="p-field"><label>Vistoria (opcional)</label><input class="form-control" name="vistoria_id" value="<?= h($_GET['vistoria_id']??'') ?>" placeholder="ID da vistoria relacionada"></div>
  </div><button class="btn btn-primary" style="margin-top:16px"><i class="fa-solid fa-folder-plus"></i> Criar dossiê</button>
 </form></div></section>
 <script>function sincronizarCliente(){const o=document.getElementById('embarcacao').selectedOptions[0];if(o&&o.dataset.cliente)document.getElementById('cliente').value=o.dataset.cliente}document.getElementById('embarcacao').addEventListener('change',sincronizarCliente);sincronizarCliente();</script>
 <?php else: ?>
 <section class="card"><div class="card-body"><div class="p-grid">
  <div><small>Embarcação</small><br><strong><?= h($d['embarcacao_nome']) ?></strong></div><div><small>Cliente</small><br><strong><?= h($d['cliente_nome']?:'Não informado') ?></strong></div>
  <div><small>Situação atual</small><br><span class="p-chip"><?= h($labels[$d['status']]??$d['status']) ?></span></div><div><small>Protocolo oficial / SISAP</small><br><strong><?= h($d['protocolo_externo_numero']?:'Ainda não registrado') ?></strong></div>
  <?php if($d['url_consulta']): ?><div style="grid-column:1/-1"><a target="_blank" rel="noopener" href="<?= h($d['url_consulta']) ?>"><i class="fa-solid fa-arrow-up-right-from-square"></i> Consultar no portal oficial</a> <small>— o número interno AM-PROT não substitui o protocolo da Marinha.</small></div><?php endif; ?>
 </div></div></section>

 <section class="p-section"><h2>Linha do tempo</h2>
  <div class="p-timeline"><?php foreach($movs as $m): ?><article class="p-event" id="mov-<?= h($m['id']) ?>"><div class="p-event-head"><div><span class="p-chip">Evento <?= str_pad((string)$m['sequencia'],2,'0',STR_PAD_LEFT) ?> · <?= h($m['tipo']) ?></span> <strong><?= h(str_replace('_',' ',$m['natureza'])) ?></strong></div><span><?= formatarDataCompleta($m['movimentado_em']) ?></span></div>
   <p><strong><?= h($m['origem_nome']) ?></strong> → <strong><?= h($m['destino_nome']) ?></strong><br><small><?= h($m['cidade'].'/'.$m['uf'].' · '.$m['meio_envio'].($m['codigo_rastreio']?' · rastreio '.$m['codigo_rastreio']:'')) ?></small></p>
   <p><?= (int)$m['itens_total'] ?> documento(s) · status <?= h($m['status']) ?><?php if($m['retifica_movimentacao_id']): ?> · retificação vinculada<?php endif; ?></p>
   <div class="p-actions"><?php if(in_array($m['status'],['CONFIRMADA','RETIFICADA'],true)): ?><a class="btn btn-sm btn-secondary" target="_blank" href="<?= APP_URL ?>protocolos/pdf?id=<?= urlencode($m['id']) ?>"><i class="fa-solid fa-file-pdf"></i> PDF</a><?php endif; ?>
   <?php if($m['status']==='RASCUNHO'&&!$somenteLeitura): ?><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="confirmar"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><input type="hidden" name="movimentacao_id" value="<?= h($m['id']) ?>"><button class="btn btn-sm btn-primary" onclick="return confirm('Confirmar e congelar esta movimentação?')">Confirmar e gerar PDF</button></form><?php endif; ?>
   <?php if($m['status']==='CONFIRMADA'&&!$somenteLeitura): ?><a class="btn btn-sm btn-secondary" href="<?= APP_URL ?>protocolos/form?id=<?= urlencode($id) ?>&retificar=<?= urlencode($m['id']) ?>#nova-mov">Retificar</a><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="criar_aceite"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><input type="hidden" name="movimentacao_id" value="<?= h($m['id']) ?>"><button class="btn btn-sm btn-secondary">Gerar link de aceite</button></form><?php endif; ?></div>
  </article><?php endforeach; ?><?php if(!$movs): ?><div class="p-note">Nenhuma movimentação registrada. A primeira normalmente é a entrada dos documentos entregues à Amazon Naval.</div><?php endif; ?></div>
 </section>

 <?php if(!$somenteLeitura): ?><section class="card p-section" id="nova-mov"><div class="card-body"><h2><?= $retificar?'Retificar evento confirmado':'2. Nova entrada ou saída' ?></h2><?php if($retificar): ?><div class="p-note">A retificação criará um novo evento. O anterior continuará preservado e será marcado como retificado.</div><?php endif; ?>
 <form method="post" action="<?= APP_URL ?>protocolos/actions" id="mov-form"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="adicionar_movimentacao"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><input type="hidden" name="idempotency_key" value="<?= h(bin2hex(random_bytes(16))) ?>"><input type="hidden" name="retifica_movimentacao_id" value="<?= h($retificar) ?>">
  <div class="p-grid">
   <div class="p-field"><label>Sentido *</label><select class="form-control" name="tipo" required><option value="ENTRADA">Entrada — Amazon recebe</option><option value="SAIDA">Saída — Amazon entrega/envia</option></select></div>
   <div class="p-field"><label>Natureza *</label><select class="form-control" name="natureza" required><option value="RECEBIMENTO_CLIENTE">Recebimento do cliente/representante</option><option value="ENVIO_ORGAO">Envio à Marinha</option><option value="RETORNO_ORGAO">Retorno/exigência da Marinha</option><option value="CUMPRIMENTO_EXIGENCIA">Cumprimento de exigência</option><option value="RETIRADA_ORGAO">Retirada no órgão</option><option value="ENTREGA_CLIENTE">Entrega ao cliente</option><option value="TRANSFERENCIA_INTERNA">Transferência interna</option><option value="OUTRA">Outra movimentação</option></select></div>
   <div class="p-field"><label>Origem *</label><select class="form-control" name="origem_tipo"><?php foreach(['CLIENTE','REPRESENTANTE','AMAZON_NAVAL','CAPITANIA','DELEGACIA','AGENCIA','CORREIOS','TRANSPORTADORA','OUTRO'] as $v): ?><option><?= $v ?></option><?php endforeach; ?></select><input class="form-control" style="margin-top:6px" name="origem_nome" required placeholder="Nome de quem entrega"></div>
   <div class="p-field"><label>Destino *</label><select class="form-control" name="destino_tipo"><?php foreach(['AMAZON_NAVAL','CLIENTE','REPRESENTANTE','CAPITANIA','DELEGACIA','AGENCIA','CORREIOS','TRANSPORTADORA','OUTRO'] as $v): ?><option><?= $v ?></option><?php endforeach; ?></select><input class="form-control" style="margin-top:6px" name="destino_nome" required placeholder="Nome de quem recebe"></div>
   <div class="p-field"><label>Unidade marítima</label><select class="form-control" name="unidade_maritima_id" id="unidade"><option value="">Selecione quando houver envio à Marinha</option><?php foreach($unidades as $u): ?><option value="<?= h($u['id']) ?>" data-cidade="<?= h($u['cidade']) ?>" data-uf="<?= h($u['uf']) ?>"><?= h($u['nome'].' — '.$u['cidade'].'/'.$u['uf']) ?></option><?php endforeach; ?></select></div>
   <div class="p-field"><label>Data e hora *</label><input class="form-control" type="datetime-local" name="movimentado_em" required value="<?= date('Y-m-d\TH:i') ?>"></div>
   <div class="p-field"><label>Cidade *</label><input class="form-control" id="cidade" name="cidade" required></div><div class="p-field"><label>UF *</label><input class="form-control" id="uf" name="uf" maxlength="2" required></div>
   <div class="p-field"><label>Meio de envio *</label><select class="form-control" name="meio_envio"><?php foreach(['PRESENCIAL','EMAIL','PORTAL','CORREIOS','TRANSPORTADORA','MENSAGEIRO','OUTRO'] as $v): ?><option><?= $v ?></option><?php endforeach; ?></select></div>
   <div class="p-field"><label>Portador / rastreio</label><input class="form-control" name="portador_nome" placeholder="Portador"><input class="form-control" style="margin-top:6px" name="codigo_rastreio" placeholder="Código de rastreio"></div>
   <div class="p-field"><label>Vínculo com protocolo anterior</label><select class="form-control" name="protocolo_anterior_id"><option value="">Sem vínculo</option><?php foreach($movs as $m): if($m['status']!=='RASCUNHO'): ?><option value="<?= h($m['id']) ?>">Evento <?= str_pad((string)$m['sequencia'],2,'0',STR_PAD_LEFT) ?> — <?= h(str_replace('_',' ',$m['natureza'])) ?></option><?php endif; endforeach; ?></select></div>
   <div class="p-field"><label>Observações</label><textarea class="form-control" name="observacoes"></textarea></div>
  </div>
  <h3 style="margin-top:20px">3. Documentos apresentados</h3><p>Selecione os documentos sugeridos ou descreva outro item. Os dados serão congelados na confirmação.</p>
  <div id="docs"></div><button class="btn btn-secondary" type="button" id="add-doc"><i class="fa-solid fa-plus"></i> Adicionar documento</button>
  <div style="margin-top:18px"><button class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Salvar movimentação para conferência</button></div>
 </form></div></section><?php endif; ?>

 <div class="p-grid p-section">
  <section class="card"><div class="card-body"><h2>Protocolo oficial</h2><p>Registre o número fornecido pela unidade após o atendimento. Ele permanece separado do AM-PROT.</p>
  <?php if(!$somenteLeitura): ?><form method="post" enctype="multipart/form-data" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="protocolo_externo"><input type="hidden" name="dossie_id" value="<?= h($id) ?>">
   <div class="p-field"><label>Número SISAP/protocolo *</label><input class="form-control" name="protocolo_externo_numero" required value="<?= h($d['protocolo_externo_numero']) ?>"></div>
   <div class="p-field"><label>Unidade *</label><select class="form-control" name="unidade_maritima_id" required><option value="">Selecione</option><?php foreach($unidades as $u): ?><option value="<?= h($u['id']) ?>" <?= $d['unidade_maritima_id']===$u['id']?'selected':'' ?>><?= h($u['nome']) ?></option><?php endforeach; ?></select></div>
   <div class="p-field"><label>Data/hora oficial *</label><input class="form-control" type="datetime-local" name="protocolo_externo_em" required value="<?= $d['protocolo_externo_em']?date('Y-m-d\TH:i',strtotime($d['protocolo_externo_em'])):'' ?>"></div>
   <div class="p-field"><label>Validade indicada</label><input class="form-control" type="date" name="validade" value="<?= h($d['protocolo_externo_validade']) ?>"></div>
   <div class="p-field"><label>Foto/PDF do comprovante</label><input class="form-control" type="file" name="comprovante" accept=".pdf,.jpg,.jpeg,.png"></div><button class="btn btn-primary" style="margin-top:12px">Registrar protocolo oficial</button>
  </form><?php endif; ?></div></section>
  <section class="card"><div class="card-body"><h2>Comprovantes e recibos</h2>
  <?php foreach($comprovantes as $a): ?><p><a target="_blank" href="<?= APP_URL ?>protocolos/arquivo?id=<?= urlencode($a['id']) ?>"><?= h($a['nome_original']) ?></a><br><span class="p-hash">SHA-256 <?= h($a['sha256']) ?></span></p><?php endforeach; ?><?php if(!$comprovantes): ?><p class="text-muted">Nenhum comprovante anexado.</p><?php endif; ?>
  <?php if(!$somenteLeitura): ?><form method="post" enctype="multipart/form-data" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="anexar_comprovante"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><select class="form-control" name="tipo_comprovante"><option value="RECIBO">Recibo</option><option value="COMPROVANTE_ENTREGA">Comprovante de entrega</option><option value="RASTREIO">Rastreio</option><option value="OUTRO">Outro</option></select><select class="form-control" style="margin-top:6px" name="movimentacao_id"><option value="">Vincular somente ao dossiê</option><?php foreach($movs as $m): if($m['status']!=='RASCUNHO'): ?><option value="<?= h($m['id']) ?>">Evento <?= str_pad((string)$m['sequencia'],2,'0',STR_PAD_LEFT) ?></option><?php endif; endforeach; ?></select><input class="form-control" style="margin-top:6px" type="file" required name="comprovante" accept=".pdf,.jpg,.jpeg,.png"><button class="btn btn-secondary" style="margin-top:8px">Anexar</button></form><?php endif; ?>
  </div></section>
 </div>
 <?php if(!$somenteLeitura): ?><section class="card p-section"><div class="card-body"><h2>Andamento informado pelo órgão</h2><p>Use para registrar análise, exigência, disponibilidade ou retirada sem modificar os eventos documentais anteriores.</p><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="andamento_orgao"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><div class="p-grid"><select class="form-control" name="novo_status"><option value="PROTOCOLADO">Protocolado</option><option value="EM_ANALISE_NO_ORGAO">Em análise no órgão</option><option value="EM_EXIGENCIA">Em exigência</option><option value="A_DISPOSICAO">Documento à disposição</option><option value="RETIRADO">Retirado</option></select><input class="form-control" required name="andamento_observacao" placeholder="Fonte, data e detalhe da informação"></div><button class="btn btn-secondary" style="margin-top:10px">Registrar andamento</button></form></div></section><?php endif; ?>
 <?php if($originais): ?><section class="card p-section"><div class="card-body"><h2>Custódia de originais físicos</h2><?php foreach($originais as $o): ?><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid #e2eae6"><div><strong><?= h($o['descricao']) ?></strong><br><small>Recebido no evento <?= str_pad((string)$o['sequencia'],2,'0',STR_PAD_LEFT) ?> · <?= $o['devolvido_em']?'Devolvido em '.formatarDataCompleta($o['devolvido_em']):'Sob custódia da Amazon Naval' ?></small></div><?php if(!$o['devolvido_em']&&!$somenteLeitura): ?><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="registrar_devolucao"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><input type="hidden" name="item_id" value="<?= h($o['id']) ?>"><button class="btn btn-sm btn-secondary" onclick="return confirm('Confirmar a devolução deste original?')">Registrar devolução</button></form><?php endif; ?></div><?php endforeach; ?></div></section><?php endif; ?>
 <section class="card p-section"><div class="card-body"><h2>Auditoria</h2><?php foreach($auditoria as $a): ?><p><strong><?= h($a['evento']) ?></strong> · <?= formatarDataCompleta($a['criado_em']) ?> · <?= h($a['usuario_nome']?:'Acesso público') ?><br><small><?= h($a['detalhe']) ?></small></p><?php endforeach; ?></div></section>
 <?php if(!$somenteLeitura): ?><section class="card p-section"><div class="card-body p-actions"><form method="post" action="<?= APP_URL ?>protocolos/actions"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="encerrar"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><button class="btn btn-secondary" onclick="return confirm('Encerrar este dossiê?')">Encerrar dossiê</button></form><form method="post" action="<?= APP_URL ?>protocolos/actions" onsubmit="return confirm('Cancelar sem apagar o histórico?')"><input type="hidden" name="csrf_token" value="<?= h(gerarCSRF()) ?>"><input type="hidden" name="action" value="cancelar"><input type="hidden" name="dossie_id" value="<?= h($id) ?>"><input class="form-control" name="motivo" required placeholder="Motivo obrigatório"><button class="btn btn-danger">Cancelar</button></form></div></section><?php endif; ?>
 <?php endif; ?>
</main>
<?php if($id!==''&&!in_array(($d['status']??''),['ENCERRADO','CANCELADO'],true)): ?><script>
const catalogo=<?= json_encode(array_map(fn($x)=>['id'=>$x['id'],'nome'=>$x['nome'],'categoria'=>$x['categoria']],$catalogo),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;let docIndex=0;
function addDoc(){const i=docIndex++,row=document.createElement('div'),options=catalogo.map(x=>`<option value="${x.id}" data-nome="${x.nome.replaceAll('"','&quot;')}" data-cat="${x.categoria}">${x.nome}</option>`).join('');row.className='p-doc';row.innerHTML=`<div><select class="form-control cat"><option value="">Outro documento (identificar)</option>${options}</select><input class="form-control desc" style="margin-top:5px" name="item_descricao[${i}]" required placeholder="Descrição exata"><input type="hidden" class="cat-id" name="item_catalogo_id[${i}]"><input type="hidden" class="categoria" name="item_categoria[${i}]" value="OUTROS"></div><select class="form-control" name="item_suporte[${i}]"><option>FISICO</option><option>DIGITAL</option></select><select class="form-control" name="item_forma[${i}]"><option>ORIGINAL</option><option value="COPIA_SIMPLES">Cópia simples</option><option value="COPIA_AUTENTICADA">Cópia autenticada</option><option value="NATO_DIGITAL">Nato-digital</option><option>DIGITALIZADO</option></select><input class="form-control" type="number" min="1" name="item_quantidade[${i}]" value="1"><div><input class="form-control" name="item_revisao[${i}]" placeholder="Nº/revisão"><input class="form-control" type="date" name="item_data[${i}]"><input class="form-control" name="item_condicao[${i}]" placeholder="Condição"><label><input type="checkbox" name="item_devolucao[${i}]" value="1"> Exige devolução</label></div><button class="btn btn-sm btn-danger" type="button" aria-label="Remover">×</button>`;row.querySelector('.cat').onchange=e=>{const o=e.target.selectedOptions[0];row.querySelector('.cat-id').value=e.target.value;row.querySelector('.desc').value=o.dataset.nome||'';row.querySelector('.categoria').value=o.dataset.cat||'OUTROS'};row.querySelector('button').onclick=()=>row.remove();document.getElementById('docs').append(row)}
document.getElementById('add-doc').onclick=addDoc;addDoc();document.getElementById('unidade').onchange=e=>{const o=e.target.selectedOptions[0];if(o.dataset.cidade){document.getElementById('cidade').value=o.dataset.cidade;document.getElementById('uf').value=o.dataset.uf}};
</script><?php endif; ?>
<?php require __DIR__.'/../../includes/footer.php'; ?>
